### ISSUE TITLE
From<Bytes> for Pages impl shouldn't round down

### ISSUE THREAD

**Issue by sfackler** [wasmerio/wasmer#1010]
The implementation of `From<Bytes>` for `Pages` simply divides the number of bytes by 65536. This means that `Pages::from(Bytes(15)) == Pages(0)`, while it seems like you'd probably want it to round up and equal `Pages(1)` (i.e. the number of pages required to store that amount of bytes).

https://github.com/wasmerio/wasmer/blob/master/lib/runtime-core/src/units.rs#L84-L88

**Comment by MarkMcCaskey** [comment]
Thanks for reporting this!  I'll take a look later and see if I can figure out what behavior makes sense depending on how it's used!  In either case, we should clearly document the behavior

**Comment by webmaster128** [comment]
In https://github.com/wasmerio/wasmer/pull/1914 `From<Bytes> for Pages` was changed to `TryFrom<Bytes> for Pages` in order to avoid silently ignoring `u32` overflows. It also adds tests to manifest the current rounding behaviour.

I think it is hard to tell which bahaviour is the right one. When calculating bytes -> pages in a memory limit, you don't want to round up because the limit would be exceeded. It is probably best to remove the `TryFrom` implementation completely and create explicit helper functions instead.

**Comment by Hywan** [comment]
This issue is closed by #1914 for what I can see. The `From<Bytes>` implementation for `Page` has been removed in favor of `TryFrom<Bytes>`. Thanks!
