### ISSUE TITLE
Expose all CallError details to C API

### ISSUE THREAD

**Issue by AdamSLevy** [wasmerio/wasmer#1046]
### Motivation

Currently details about CallErrors are hidden from the C API. In particular it is not possible to detect the ExecutionLimitExceededError that is thrown from the metering middleware. 

### Proposed solution

Either expose more details about errors, possibly simply through the error string, or expose a special error string for ExecutionLimitExceededErrors.

**Comment by Hywan** [comment]
Hello @AdamSLevy,

Since Wasmer 1.0, we are providing a new C API. With Wasmer 2.0, the old C API has been deprecated.

That being said, with the new C API (`wasmer-c-api`) based on Wasm C API, we provide an “unstable” Rust module, which expose a middleware API: https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/unstable/middlewares/metering/index.html (introduced in https://github.com/wasmerio/wasmer/pull/2103).

This documentation contains an example that shows when `wasm_func_call` returns a non-null `wasm_trap_t`, and how `wasmer_metering_points_are_exhausted` can be used to detected whether the metering points are exhausted or not.

I'm closing this issue as I believe your feature request is now implemented.
