### ISSUE TITLE
Is there away to allow an application to open a TCP socket?

### ISSUE THREAD

**Issue by gkorland** [wasmerio/wasmer#1110]
We have a C application that opens a TCP socket, is there a way to allow/control which TCP can be opened?

**Comment by Neightro** [comment]
I'm just a lurker here; I came here looking for information on the same subject. My understanding (and I'm still quite unfamiliar with WebAssembly) is that it's not possible to open just any socket on the system from WebAssembly; you will have to open a socket from outside WebAssembly and then pass it to the runtime. You will then be able to read and write the socket via WASI; [This thread](https://github.com/wasmerio/wasmer/issues/583) implies that it functions similarly to POSIX systems, wherein the socket is manipulated like a file descriptor. 

I would also suggest looking into the documentation for Wasmer; you might find more detailed information than with which I am able to provide you. I'm going to do some more reading; I will update if I learn more details; I will include links if I come across anything relevant.

**Comment by MarkMcCaskey** [comment]
@Neightro Thanks! That's good information.

Sorry about the lack of response to this issue, it must have fallen through the cracks.

Yeah, opening sockets depends on your ABI providing imports that let you do so.  Our Emscripten implementation, which is minimally/not sandboxed allows programs to use sockets.  Additionally, you can do the "no ABI", or rather the "custom ABI" approach where you implement a socket API yourself with imports so that it works with your program.

> I'm not sure if Wasmer currently supports sockets; I can see constants relating to sockets in the Rust wasmer-wasi documentation, though I've yet to find any specific information on how to use sockets with WASI. I would appreciate someone with more knowledge could help fill in that gap in my knowledge.

I believe we have some experimental code in `kernel-net`, but I'm not familiar with it.  Sockets are not yet well defined in WASI so we don't support them yet.  When WASI gets to a place where the CG can start discussing socket APIs in more depth, we'll definitely prioritize the development and implementation of those APIs.

It is possible to use the WASI virutal filesystem to implement networked files (the same way we implemented the framebuffer).  It's a hack but it's something you could do today if you wanted to have networked WASI applications in Wasmer.  The biggest issue with the hacks such as custom imports or special files is that no existing socket code will "just work" with it.

**Comment by CooperLi** [comment]
@MarkMcCaskey any updates for socket support now despite the wasi virtual fs network files implementation? : )

**Comment by syrusakbary** [comment]
We have a work-in-progress branch that fully supports sockets:

https://github.com/wasmerio/wasmer/tree/wasio

**Comment by Hywan** [comment]
We have another branch (a reb00t) with socket and epoll support, https://github.com/wasmerio/wasmer/tree/wasio-reboot-event-based-socket2/lib/wasi-experimental-network/examples. There is a Rust frontend, and implementation in WASI libc and Zig is also coming, https://github.com/ziglang/zig/compare/master...Hywan:feat-wasi-experimental-networking?expand=1. `socket.h` and `epoll.h` are compiling and working.

Note: It's super experimental for the moment. The idea is not to make it the new standard but to experiment as a community, and see what's missing, what are the challenges etc.

**Comment by AlmogBaku** [comment]
Any update on this?

**Comment by epilys** [comment]
This was added in 62de9c5aad6c2eaf572d461990fd8dfe7896c8b7 which has been merged to master, and will be part of the 3.0 release
