### ISSUE TITLE
is it possible to capture something mutable in imports! closures?

### ISSUE THREAD

**Issue by thedavidmeister** [wasmerio/wasmer#1175]
### Motivation

code like this:

```rust
pub fn wasm_instance_factory(runtime: &mut Runtime, module: &Module) -> Result<Instance, HolochainError> {
    let (sender, receiver) = channel();
    let import_object = imports! {
        "env" => {
            "hc_debug" => func!(|ctx: &mut Ctx, ptr: u32, len: u32| -> ZomeApiResult {
                invoke_debug(runtime, try_parameters_json(runtime, ptr, len)?.try_into()?)
            }),
        },
    };
```

produces:

```rust
error[E0525]: expected a closure that implements the `Fn` trait, but this closure only implements `FnMut`
  --> crates/core/src/wasm_engine/factories.rs:71:33
   |
71 |             "hc_debug" => func!(|ctx: &mut Ctx, ptr: u32, len: u32| -> ZomeApiResult {
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this closure implements `FnMut`, not `Fn`
72 |                 invoke_debug(runtime, try_parameters_json(runtime, ptr, len)?.try_into()?)
   |                              ------- closure is `FnMut` because it mutates the variable `runtime` here
   | 
  ::: <::wasmer_runtime_core::macros::func macros>:1:24
   |
1  | ($ func : expr) => { { $ crate :: Func :: new ($ func) } } ;
   |                        ---------------------- the requirement to implement `Fn` derives from here
```

is it possible to capture mutable things in imported closures?

### Proposed solution

unsure

### Alternatives

unsure

**Comment by MarkMcCaskey** [comment]
No, not directly because that would violate Rust's ownership rules.  Wasmer 0.13.1 currently allows non-`Send` closures but we're changing this in 0.14.0, so the solution is to use something like `Arc<Mutex<T>>` or `Arc<RefCell<T>>` if you can guarantee that host calls can't run concurrently.

It's possible to use unsafe here to do what `Ctx.data` is doing as well, use `Box::into_raw` and move copies of the pointer into the closures and have the closures cast that into a `&mut T` using `unsafe`.  You'd have to clean up the memory yourself though when ImportObject gets dropped though.

Closing this now because I think that's a complete answer, feel free to respond or open another issue though!
