### ISSUE TITLE
wasm failed to invoke functions when running wasm file with wasmtime

### ISSUE THREAD

**Issue by Montana** [wasmerio/wasmer#1205]
Hey guys! 

I wanted to build a "C" version of the following: 

```rust
#[wasm_bindgen]
pub fn render(input: &str) -> String {
    let parser = Parser::new(input);
    let mut html_output = String::new();
    html::push_html(&mut html_output, parser);
    return html_output;
}
```
I used wasi-libc and tried to build a simple "Hello World" program with Clang via: 

``` C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int foo1()
{
    printf("Hello foo1()\n");
    return 0;
}

int foo2(char* filename)
{
    printf("Hello foo2()\n");
    printf("filename is %s\n", filename);
    return 0;
}
```

The invoke function error: 

```C
wasmtime test.wasm --invoke foo1
Hello foo1()
warning: using `--render` with a function that returns values is experimental and may break in the future
0

$ wasmtime test.wasm --invoke foo2 "hello"
warning: using `--render` with a function that takes arguments is experimental and may break in the future
error: failed to process main module `test.wasm`
    caused by: invalid digit found in string
```

Is Rust currently the only way to build a wasm lib file? I've seen a similar problem on this, but was seeing if I could get some different results posting on here, for context I'm testing this and Emscripten. 

Thanks in advance! 

-Montana

**Comment by MarkMcCaskey** [comment]
So it's worth noting that the two examples you posted aren't the same, one is passing a string as an argument and the other is not.  The error message, "    caused by: invalid digit found in string" implies this as well.  Wasmtime's `invoke` seems to only handle numbers (I believe ours is the same, I haven't looked at that code in a while).

It's not possible in general to invoke functions safely with strings right now.  The reason is that strings require memory allocation and memory allocation is done on a per-ABI basis.  Some ABIs may not safely support the host allocating guest memory at all (like WASI), given that, the only option is to arbitrarily overwrite part of memory and hope that the guest program doesn't try to use that memory.  That's my best guess as to why this isn't a feature that you're seeing more generally.

WASI does have a way to pass arguments, however, so it if the argument data structure is initialized and the host can figure out where that is, then it may be possible to make this work, though I don't know how that would work to be honest.

You can try filing an issue on the WasmTime repo but I don't think you'll get a better response; perhaps you want to file an issue on the WASI repo about host allocation of guest memory for purposes like this!

**Comment by MarkMcCaskey** [comment]
As an alternative for Wasmer: I've thought about having a little command line interface allowing the user to specify values to load into Wasm memory, which is effectively a more verbose way of doing the same thing but puts the burden of correctly using memory (a currently impossible in general task) on the user, so that they can make it work for their specific use case.

It's just a matter of priorities and time that I haven't implemented this yet.  If you're interested in working on this, I'd be happy to mentor you!
