### ISSUE TITLE
Passing complicated traits to WASM

### ISSUE THREAD

**Issue by KaiserKarel** [wasmerio/wasmer#1227]
Is it possible to pass trait objects to wasm using the ImportObject? 

For example an http client which is constructed at runtime by the host. In my case I want the host to provide some context and certificates which might change during the runtime of the wasm code. I'm having my wasm code construct http requests and want the host to execute them, returning the responses.

**Comment by MarkMcCaskey** [comment]
Hmm, I think I probably don't fully understand the question, but Wasm memory and host memory are completely separate, so the only way to make things like "a change on the host reflects on the guest" work is through generating code that does that.

If you mean using a trait object as a way to have a single interface across the host/guest boundary with different configuration then the answer is kind of but effectively no.  Wasm is sufficiently low level that using the real trait interface directly right now would require generating code on probably both the Wasm side and the Host side at compile time to handle all possible cases and then you'd have to reimplement trait dispatch that way too.  In any case if this is possible, it's not a generic solution and probably not worth the effort.

I think the simplest path forward right now is to figure out the flow of data and design an ABI around that.  There are a few ways to structure the Wasm guest and Host relationship.  In a guest dominated design, the guest is the primary executor and would poll the host or the host-calls would do a check for new information on each call.  In a Host dominated design, the host would call setters on the guest when the new information comes in.  This kind of thing is pretty low level, and it's just a matter of if you want the guest staying in a loop or if you want the host to call into the guest on a loop/events received.

In reality, the Host can always set limits on execution and always has the ability to be in full control of the guest, it's more of an aesthetic design choice.  For untrusted code, a Host-dominated system is probably more straight-forward, especially if you want to easily run multiple guests.

Please follow up if you have any more questions, this is a bit tricky and we're happy to help with some of the design here.

**Comment by KaiserKarel** [comment]
Thanks for the elaboration. I'm working on a host dominated design. Do you have documentation on how to work with these setters? I think I can get a working prototype using host provided functions once I figure out how to pass structs from the host to the guest and vice versa. Reading the documentation it seems that I should preload the memory with the struct as [u8] and then deserialize? 

Is there a more generic approach and does this work for unsized structs?

**Comment by MarkMcCaskey** [comment]
> Do you have documentation on how to work with these setters?

The setters would just be exported functions from the Wasm Guest that the Host can call to set values.

You can implement that with global variables or you can have a mechanism (host and guest functions) that lets the host know about the memory addresses of the thing you want to change.  For example:

- Guest allocates config object and calls host `register_config(u32)` (this function can take extra information if you want for debug purposes or otherwise) so that the host can hold on to it
- Host calls `config_set_$PROPERTY(object: u32, other, arguments, here)` to update the specific entry on the guest

----

> Reading the documentation it seems that I should preload the memory with the struct as [u8] and then deserialize?

Yeah, that's fundamentally how all data transfer between the host and guest will happen when working with Wasm (in the future there may be some other, limited ways for certain use cases).  We're working on supporting features that can automate some of this for our users, but the way it will work internally is by copying data.

> does this work for unsized structs?

A size has to be known when copying.  If unsized means dynamically changing in size, then it's something that the host and guest will have to keep in sync.

---

> once I figure out how to pass structs from the host to the guest and vice versa

This is also ABI specific and there's no one correct answer.  WASI, for example, has entirely guest managed memory.  There is no standard way for a Wasm host to allocate memory when dealing with WASI.  The WASI syscalls are all designed so that all the memory is allocated ahead of time and pointers are passed to the host.  This is a common pattern in low level software to simplify ownership.  However when working on dynamic systems, you may find having the host able to get Wasm memory can simplify things, and that's a fine a design choice too.

A fundamental role of a Wasm ABI is to design a system for managing resources and sharing access to them!

----

> Also if there is a slack or other way of communicating

Sure, we can invite you to our slack!

**Comment by KaiserKarel** [comment]
Thanks for the quick replies! I'll check out the spectrum. I reckon I've got a decent idea on how to continue forward.

**Comment by MarkMcCaskey** [comment]
@KaiserKarel we just made a new Slack open to the public, feel free to join at https://slack.wasmer.io !
