### ISSUE TITLE
support CLI framebuffer

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer#1277]
### Motivation

let non desktop systems also write to framebuffer using wasi. 

### Proposed solution

libw::write_text("/_wasmer/dev/fb0/virtual_size","terminal").unwrap();

as an option to use terminal's framebuffer

### Alternatives

this isn't possible right now at all anywhere else

**Comment by MarkMcCaskey** [comment]
This is a neat idea, I don't have context on what is required to make this work, if it's forwarding writes to platform specific locations then that seems easy enough!

I don't think this is something I'll be able to prioritize soon, but I'd be happy to mentor anyone interested in designing and implementing this

**Comment by MarkMcCaskey** [comment]
Tagging as "Good first issue" because I think this should be fairly straight-forward and we'll work with the implementer.  This update will probably require a bit of familiarity with Rust though, as we'll probably want to refactor the existing code behind a trait so that the rest of the code can be decoupled from the specific framebuffer implementation.

**Comment by humancalico** [comment]
@richardanaya I'll work on this

**Comment by MarkMcCaskey** [comment]
@humancalico Glad to hear it! Feel free to message us on slack or ask questions here if you run into any problems or don't know where to start
