### ISSUE TITLE
I do NOT like wax magic!

### ISSUE THREAD

**Issue by KSXGitHub** [wasmerio/wasmer#1297]
### Motivation

The new release of wasmer provides `wax` which is just a symlink to `wapm`. This means that `wapm` must do magic, this also means that `wax` cannot be renamed to something else.

### Proposed solution

Create a separate program named `wax` that executes `wapm execute`.

**Comment by Hywan** [comment]
Sorry if the design of `wax` annoys you. We will come back to you shortly.

**Comment by frank-dspeed** [comment]
he simply wants to have separated code that's not a priority he can issue a pr to help that this faster happens.

**Comment by KSXGitHub** [comment]
@Hywan It's not just an annoyance. It's a limitation. I have explained that limitation.

@frank-dspeed I don't want to sound rude, but proper punctuations may help me understand you better.

**Comment by frank-dspeed** [comment]
@KSXGitHub give me an example of the limits I do not understand magic it is not in the source.

as far as i understood you. You are not happy that wax shares code with wapm

**Comment by syrusakbary** [comment]
Sorry for the delay replying here.

Yeah, it's true that wax is doing magic in some sense. We are using a strategy coined by [busybox](https://busybox.net/), that basically uses only one binary and multiple commands (symlinks) pointing at it. In that sense, depending on the command name used it will forward the call to one or other command.

Before choosing that approach we discussed about having instead a `wax` with:

```bash
#!/bin/bash
wapm execute ${@}
```

However, we discarded it because it introduced a small extra lag. At the same time, our strategy still allows that, so anyone can still do the `wapm execute ...` strategy in cases they need.

@KSXGitHub I'm aware you maintain some Wasmer packages for linux distribution. Is the strategy we are using bad for packaging it or so?

**Comment by frank-dspeed** [comment]
@syrusakbary maybe a it should be better like git :) wasmer pm => wasmer-pm
a single binary that calls other binarys.

**Comment by syrusakbary** [comment]
Wapm and WAX share a lot of logic (almost all). If we were to split out in two different binaries, the download sizes will be much bigger. In that sense wax is built to be "inside" wapm rather than a plugin.

However we are investigating the `wasmer pm` => `wasmer-pm` approach for other kind of plugins :)

**Comment by frank-dspeed** [comment]
@syrusakbary i think he would be happy if wax would not be a symlink when it would be something that calls wapm this is solved :+1:

**Comment by KSXGitHub** [comment]
> Before choosing that approach we discussed about having instead a `wax` with:
> 
> ```shell
> #!/bin/bash
> wapm execute ${@}
> ```
> 
> However, we discarded it because it introduced a small extra lag. At the same time, our strategy still allows that, so anyone can still do the `wapm execute ...` strategy in cases where is need.

That extra lag is insignificant in my opinion. You can optimize it by not relying on `bash` or any third-party shell interpreter, instead, create a Rust program that executes `wapm execute` directly.

> I'm aware you maintain Wasmer packages for some Linux distributions. Is the strategy we are using bad for packaging it or so?

True. Symlinks are tricky to copy. The only way to creates `wax` is to enter installation target (`/usr/bin/`) and create a new `wax -> wapm` symlink, which is an unusual practice. This essentially recreates implementation details of `wax`, which is also something I am not happy about.

**Comment by syrusakbary** [comment]
Sounds good @KSXGitHub, thanks for your feedback!

We will fix it for the next version of Wasmer 🙂

**Comment by syrusakbary** [comment]
We are working now in a refactor that will land soon in master.

We solved the wax logic there :)

**Comment by syrusakbary** [comment]
Thanks to the refactor that has just landed in `master`, we have updated the code regarding `wax`, and is now it's own bash script file.
https://github.com/wasmerio/wasmer/blob/master/Makefile#L147-L148

Closing the issue
