### ISSUE TITLE
Passing fn as parameter in host or guest

### ISSUE THREAD

**Issue by Alphapage** [wasmerio/wasmer#1302]
Hello,

I'd like to know if it is possible to do something like this in host or guest:
```
extern fn afunction(

    param1: fn(data1: Option<Vec<u8>>, data2: Option<Vec<u8>>),

    param2: Vec<u8>

) -> Option<Vec<u8>> {

    param1(mydata1,mydata2);
...
}
```

Thank you in advance for your help.

**Comment by MarkMcCaskey** [comment]
Yes, it is possible to call guest functions from the host with [Ctx::call_with_table_index](https://docs.rs/wasmer-runtime/0.16.2/wasmer_runtime/struct.Ctx.html#method.call_with_table_index).  When compiling to Wasm, Rust will instead insert the function into a table and pass a table index instead of a function pointer, so using it as a table index with that method on `Ctx` should work!

The guest cannot call functions on the host currently, other than through imports.  If you wanted something more dynamic, you could do the equivalent of inserting function pointers into data on the `Ctx` and passing table indices into the guest and having a dedicated import from the host that allows invoking functions.

Let me know if you run into any issues with it and I'll help you fix it!
