### ISSUE TITLE
RuntimeError is not always downcastable to the host error

### ISSUE THREAD

**Issue by nearmax** [wasmerio/wasmer#1328]
### Describe the bug

In Rust, sometimes `wasmer_runtime::error::RuntimeError` returned by Wasmer is not downcast-able to the error type that our host function returns to Wasmer.

* Here is we try to downcast it:
https://github.com/nearprotocol/nearcore/blob/a08944db6672185618e2454fce5e7be0e327b47a/runtime/near-vm-runner/src/errors.rs#L59
* And here is the place where all host functions return only `VMLogicError `https://github.com/nearprotocol/nearcore/blob/05a82d8dd74531b21567623ab0e7e75946afea19/runtime/near-vm-runner/src/imports.rs#L7

Versions:
```
wasmer-runtime = { version = "0.11.0", features = ["default-backend-singlepass"], default-features = false }
wasmer-runtime-core = { version = "0.11.0", features = ["backend-singlepass"]}
```

### Expected behavior
`RuntimeError` to be always downcastable to the error returned by the host functions.

### Actual behavior
Sometimes we are getting error that cannot be downcasted.

**Comment by MarkMcCaskey** [comment]
Thanks for the bug report!

I believe `RuntimeError` is returned in other exceptional situations to avoid panicking or terminating, for example: in [`Func::call`](https://github.com/wasmerio/wasmer/blob/master/lib/runtime-core/src/typed_func.rs#L581-L583).

It seems that when an internal `RuntimeError` is returned, it's usually either a `&'static str` or a `String`.  I'd be curious to know if the errors you're seeing can be downcast to either of those and if so, what the message is.

Additionally since, 0.14.0 it looks like we sometimes return an [`ExceptionCode`](https://docs.rs/wasmer-runtime/0.14.0/wasmer_runtime/enum.ExceptionCode.html) this way.

**Comment by nearmax** [comment]
Will try to reproduce
