### ISSUE TITLE
Please, need help with example.

### ISSUE THREAD

**Issue by aleksmelnikov** [wasmerio/wasmer#1347]
### Summary

1. I created a simple library crate:
```rust
// $cat a/src/lib.rs

#[no_mangle]
pub extern "C" fn funca() {
   println!("funca");
}

#[no_mangle]
pub extern "C" fn _start() {
}
```
And compiled it:
`cargo build --manifest-path=a/Cargo.toml --target=wasm32-wasi`

I can invoke `funca`: 
```
$wasmer run --invoke funca a/target/wasm32-wasi/debug/a.wasm
WARNING: Invoking aribtrary functions with WASI is not officially supported in the WASI standard yet.  Use this feature at your own risk!
funca
funca([]) returned []
```

2. I created a simple binary crate:
```rust
// $cat c/src/main.rs

use wasmer_runtime::{error, imports, instantiate, Func};
fn main() -> error::Result<()> {
    let wasm_bytes = include_bytes!("/at/rust/wasmer/a/target/wasm32-wasi/debug/a.wasm");
    let import_object = imports! {};
    let instance = instantiate(wasm_bytes, &import_object)?;
    let funca: Func<()> = instance.func("funca")?;
    let result = funca.call()?;
    Ok(())
}
```
And compiled it:
`cargo build --manifest-path=c/Cargo.toml`

I ran it and got:
```
$cargo run --manifest-path=c/Cargo.toml
Error: LinkError([ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_write" }])
```
What is my mistake? Thank you.

**Comment by MarkMcCaskey** [comment]
It looks like you're trying to compile a Wasm module with the WASI target and run it with Wasmer as a library.

The code above looks mostly correct but there's 1 issue that stands out: the import object, `    let import_object = imports! {};`, is empty.  The imports are the primary way that we satisfy ABI (like WASI or Emscripten) requirements.

Looking at the error we see,

```
LinkError([ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_write" }])
```

Which tells us that the Wasm module expected an import called `"wasi_snaphsot_preview1" "fd_write"`.

Because Wasmer ships an implementation of the WASI ABI we can use that to resolve these imports using the [`wasmer_wasi` crate](https://crates.io/crates/wasmer-wasi).

In `wasmer-wasi` there are a few ways to do this:
- The legacy solution: [`generate_import_object`](https://docs.rs/wasmer-wasi/0.16.2/wasmer_wasi/fn.generate_import_object.html) - gives us the latest version of WASI.  This is fine for if you're targeting the latest version of WASI only and don't mind breakage during updates.
- The flexible legacy solution: [`generate_import_object_for_version`](https://docs.rs/wasmer-wasi/0.16.2/wasmer_wasi/fn.generate_import_object_for_version.html) - this is the same as the above but lets us get the exact version that we want.  We can auto-detect the WASI version of the WASI Wasm module with the [`get_wasi_version`](https://docs.rs/wasmer-wasi/0.16.2/wasmer_wasi/fn.get_wasi_version.html) function.  This solution is more robust to future changes.
- The best solution: Use [`generate_import_object_from_state`](https://docs.rs/wasmer-wasi/0.16.2/wasmer_wasi/fn.generate_import_object_from_state.html) - this function requires a `WasiState` and a `WasiVersion`.  We can get the `WasiVersion` the same way as before and we can create a [`WasiStateBuilder`](https://docs.rs/wasmer-wasi/0.16.2/wasmer_wasi/state/struct.WasiStateBuilder.html) with [`WasiState::new`](https://docs.rs/wasmer-wasi/0.16.2/wasmer_wasi/state/struct.WasiState.html#method.new) and use the builder API to give it the information you need and then build it with [`WasiStateBuilder::build`](https://docs.rs/wasmer-wasi/0.16.2/wasmer_wasi/state/struct.WasiStateBuilder.html#method.build).  I'll write out a full example below.


```Rust
use wasmer_runtime::{error, imports, instantiate, Func};
use wasmer_wasi::{generate_import_object_from_state, get_wasi_version, state::WasiState};
fn main() -> error::Result<()> {
    let wasm_bytes = include_bytes!("/at/rust/wasmer/a/target/wasm32-wasi/debug/a.wasm");
    let mut state_builder = WasiState::new("wasi-prog-name");
    let state = state_builder
    // environment variables, arguments, and preopened directories go here
       .build()?;
    let wasi_version = get_wasi_version(wasm_bytes, true).expect("Could not detect WASI ABI in Wasm module");
    let import_object = generate_import_object_from_state(state, wasi_version);
    let instance = instantiate(wasm_bytes, &import_object)?;
    let funca: Func<()> = instance.func("funca")?;
    let result = funca.call()?;
    Ok(())
}
```


I hope that answers your questions!  I realized while writing this and going through some of our docs that our docs are missing important information here!  Thanks for the report, I'll file an issue to improve our docs here too!

**Comment by aleksmelnikov** [comment]
@MarkMcCaskey , Thank you. But your code gives the error:
```
error[E0308]: mismatched types
  --> src/main.rs:25:41
   |
25 |     let wasi_version = get_wasi_version(wasm_bytes, true).expect("Could not detect WASI ABI in Wasm module");
   |                                         ^^^^^^^^^^ expected struct `wasmer_runtime_core::module::Module`, found array `[u8; 1950410]`
   |
   = note: expected reference `&wasmer_runtime_core::module::Module`
              found reference `&[u8; 1950410]`
```
`pub fn get_wasi_version(module: &Module, strict: bool) -> Option<WasiVersion>`

And on this step I have no `Module` yet.

**Comment by MarkMcCaskey** [comment]
@aleksmelnikov You should be able to fix that with something like:

```Rust
    let module = wasmer_runtime::compile(wasm_bytes).unwrap();
    let wasi_version = get_wasi_version(&module, true).expect("Could not detect WASI ABI in Wasm module");
    ...
    let instance = module.instantiate(&import_object)?;
```

**Comment by aleksmelnikov** [comment]
@MarkMcCaskey , Thank you for the detailed answer.
