### ISSUE TITLE
Using an emscripten C++

### ISSUE THREAD

**Issue by s0l0ist** [wasmerio/wasmer#1378]
### Describe the bug

It appears wasmer cannot handle C++ bindings provided by `embind` in a C++ library that I've ported.

### Steps to reproduce

1. Clone the [node-seal repository](https://github.com/morfix-io/node-seal) recursively
2. Follow the contributions guide to get the emscripten environment set up properly
3. Run the build using the script provided (below)
4. Attempt to run via wasmer:
`wasmer run src/bin/wasmer/seal.wasm --disable-cache`

### Expected behavior

Should return nothing because this is a library and has no `main`. I'm eventually expecting to use as a library in the future.

### Actual behavior
Instead it returns 
```Error: Can't instantiate module: LinkError([ImportNotFound { namespace: "env", name: "_embind_register_class_function" }, ImportNotFound { namespace: "env", name: "_emval_decref" }, ImportNotFound { namespace: "env", name: "_embind_register_class_constructor" }, ImportNotFound { namespace: "env", name: "_embind_register_class" }, ImportNotFound { namespace: "env", name: "_emval_take_value" }, ImportNotFound { namespace: "env", name: "_emval_incref" }, ImportNotFound { namespace: "env", name: "_emval_call_void_method" }, ImportNotFound { namespace: "env", name: "_emval_get_method_caller" }, ImportNotFound { namespace: "env", name: "_emval_run_destructors" }, ImportNotFound { namespace: "env", name: "_emval_as" }, ImportNotFound { namespace: "env", name: "_emval_get_property" }, ImportNotFound { namespace: "env", name: "_emval_new_cstring" }, ImportNotFound { namespace: "env", name: "_embind_register_memory_view" }, ImportNotFound { namespace: "env", name: "_embind_register_class_class_function" }, ImportNotFound { namespace: "env", name: "_embind_register_function" }, ImportNotFound { namespace: "env", name: "_embind_register_enum_value" }, ImportNotFound { namespace: "env", name: "_embind_register_integer" }, ImportNotFound { namespace: "env", name: "_embind_register_class_property" }, ImportNotFound { namespace: "env", name: "_embind_register_enum" }, ImportNotFound { namespace: "env", name: "_embind_register_std_wstring" }, ImportNotFound { namespace: "env", name: "round" }, ImportNotFound { namespace: "env", name: "_embind_register_class_class_property" }, ImportNotFound { namespace: "env", name: "_embind_register_float" }, ImportNotFound { namespace: "env", name: "_embind_register_std_string" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_write" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_close" }, ImportNotFound { namespace: "env", name: "emscripten_notify_memory_growth" }, ImportNotFound { namespace: "env", name: "_embind_register_emval" }, ImportNotFound { namespace: "env", name: "_embind_register_bool" }, ImportNotFound { namespace: "env", name: "_embind_register_void" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_seek" }, ImportNotFound { namespace: "env", name: "__sys_read" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "environ_get" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "environ_sizes_get" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "proc_exit" }, ImportNotFound { namespace: "env", name: "__cxa_thread_atexit" }, ImportNotFound { namespace: "env", name: "_emval_call" }, ImportNotFound { namespace: "env", name: "_embind_register_smart_ptr" }])```

### Additional context
Emscripten build script:
```#!/usr/bin/env bash

# WASM build
source ./submodules/emsdk/emsdk_env.sh \
&& cd ./submodules/SEAL/native/lib/ \
&& em++ \
-Wall \
-O3 \
--bind \
-o seal.wasm \
libseal-* ../../../zlib/libz.* \
-s STANDALONE_WASM \
-s WASM=1 \
-s ALLOW_MEMORY_GROWTH=1 \
-s EXPORT_ES6=1 \
-s MODULARIZE=1 \
-s USE_ES6_IMPORT_META=0 \
-s SINGLE_FILE=0 \
--closure 1 \
&& cp seal* ../../../../src/bin/wasmer \
&& cd ../../../
```

**Comment by MarkMcCaskey** [comment]
Thanks for the report!  It looks like there's 2 things going on here:

1. is that this is using a newer version of Emscripten (our implementation only works up until about 1.38.43 or so due to the addition of WASI-like calls) which we don't actively support
2. it looks like we don't have any support for `embind_*` calls yet.

Emscripten is a bit tricky to support for a server-side runtime because it doesn't have ABI stability as a core focus.  This is because it can always generating matching JS, so it's a non-issue for them.  Additionally because of this fact, that it generates matching JS, things like minification are possible and desirable.  However this prevents arbitrary Emscripten-flavored Wasm from being usable without the JS.

Due to our size, recently we've been prioritizing some other aspects of Wasmer and likely won't be able to prioritize this in the foreseeable future.  However if someone is interested in working on this or adding support for missing calls into Emscripten, we'd be happy to help mentor you through that process!

**Comment by s0l0ist** [comment]
@MarkMcCaskey Sure I'd take a look if I knew where to start. Any tips?
