### ISSUE TITLE
How to compile c program including library?

### ISSUE THREAD

**Issue by tuandt** [wasmerio/wasmer#1383]
Hello everyone,

I have a program like this:
test.c
#include <stdlib.h>

int add_random_number(int n)
{
   return n + rand();
}

I want to compile it to .wasm file and call this function from host c program.
But when I call: wasmcc test.c -o test.wasm
There was error:

test.c:1:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
1 error generated.

Could anyone help or show me how to do that?
Thanks.

**Comment by MarkMcCaskey** [comment]
To answer your question in general, you have to provide the library!

However because most people don't want to have compile and manage libc themselves many uses of Wasm use "ABI"s to handle this case.  You can try compiling with `wasicc` for example to compile to the WASI ABI.  This will require your host to provide the WASI imports though.  We have some convenience methods in our C API to provide these imports.

You can also try using the Emscripten ABI: you'll need a copy of `emcc` from version 1.38.43 or earlier and you'll need to provide those imports!  You can compile the C API with `make capi-emscripten` to generate a new header file and libwasmer library to use emscripten as it's off by default in the C API right now.

Feel free to reopen this issue if that doesn't answer your question!
