### ISSUE TITLE
Does this work on ARM?

### ISSUE THREAD

**Issue by deian** [wasmerio/wasmer#1441]
Hey, I'm trying to get [this simple example](https://docs.rs/wasmer-runtime/0.17.0/wasmer_runtime/#heres-an-example) working on ARM but it's panicking with Cranelift and neither the LLVM nor the Singlepass backends seems to install. Do you have a working example I can build on? Thanks so much!

**Comment by igrep** [comment]
Are you trying with ARM 32bit? Wasmer currently supports only AArch64 (ARM 64bit).

**Comment by deian** [comment]
Nope, it's on ARM 64

**Comment by MarkMcCaskey** [comment]
Hi @deian ! For Singlepass you'll need to use a nightly version of Rust.  I believe our CI is currently pinned to `nightly-2019-12-18`, but more recent versions of nightly should hopefully work too.

For LLVM you'll need to set up LLVM in order to build it: https://docs.wasmer.io/ecosystem/wasmer/building-from-source#llvm-backend might be helpful here!

Let me know if that doesn't work, but @igrep is correct, Wasmer should work with Singlepass on AArch64!

**Comment by syrusakbary** [comment]
We also added support of Aarch64 with the Cranelift backend in our refactor.

**Comment by syrusakbary** [comment]
Closing the issue as even in master, is possible to target ARM with Singlepass. Cranelift coming soon.

**Comment by syrusakbary** [comment]
Update: Wasmer 1.0 can compile to ARM also from Cranelift and LLVM :)
