### ISSUE TITLE
UTF-16 string util on WasmPtr

### ISSUE THREAD

**Issue by dmfutcher** [wasmerio/wasmer#1510]
### Motivation

I've been experimenting with a Rust/Wasmer host running [Assemblyscript](https://www.assemblyscript.org/introduction.html) generated WASM. Assemblyscript Strings are very much like JS strings, so use UTF-16 encoding. The code to handle reading UTF-16 strings from a `WasmPtr` isn't super involved ([example](https://github.com/bobbo/poyekhali/commit/a9841ab7f78893478f5a2aab1cdbeb0dd566cb84#diff-d02973339db488fbaf9593a2fc360d4fR202)), but it would be easier to have support for them alongside `WasmPtr::get_utf8_string`.

### Proposed solution

Add UTF-16 equivalent of `get_utf8_string` to `WasmPtr`.

### Additional context

If there's appetite for this I'd be happy to work out a PR for it.

**Comment by syrusakbary** [comment]
We would be super happy to support it similary to utf8. Any PR would be greatly welcomed!

**Comment by bobbo** [comment]
@syrusakbary I've seen a big refactor being talked about, would I be best to wait until that drops before submitting a PR?

**Comment by MarkMcCaskey** [comment]
Thanks for the suggestion, there's actually a third-party crate for AssemblyScript utilities for Wasmer https://crates.io/crates/wasmer-as ; perhaps that will work for you!

On another note, I think we need to review `WasmPtr` as an abstraction because returning `&T` into Wasm memory isn't safe in general in Rust (and has the potential to do bad things in all languages that I'm aware of).  The issue is that the underlying memory can be mutated and the encoding can then become invalid / race conditions are possible.  This may not be an issue when running single threaded, but it's definitely an issue with threads as far as I can remember.

I'm not sure what the best solution is for this, some options are:
- tag these functions as `unsafe` in Rust
- make an abstraction that uses `read_volatile` and doesn't use a type that can have an invalid binary layout (no more `&str`)
- somehow limit this to singlethreaded use only? Unclear if that's possible or if it fully solves the issue
- have a way to temporarily make sections of Wasm memory read-only (probably has a lot of overhead, but for certain uses may be the optimal solution)

**Comment by Hywan** [comment]
Is it still active?
