### ISSUE TITLE
Generated C code with cbindgen doesn't work with MSVC

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1601]
Reported on our community slack, MSVC is not happy with empty structs:

```C
typedef struct {

} wasmer_instance_t;
```

Is not okay, but something like

```C
typedef struct wasmer_instance_t
```

was reported to probably work with MSVC.

**Comment by nlewycky** [comment]
I'll second that MSVC is correct and `typedef struct { } wasmer_instance_t;` is indeed invalid C, though intentionally accepted by clang and GCC as a compiler extension, as well as being valid C++. Both clang and GCC know to warn on it with -Wgnu-empty-struct and -Wpedantic respectively.

I'd suggest a slightly different replacement of:
```
typedef struct wasmer_instance_t wasmer_instance_t;
```
because `typedef struct wasmer_instance_t` will trigger warnings that are on-by-default in clang and gcc.

**Comment by Hywan** [comment]
The generated header files no longer contain such struct definitions. Bug is fixed.
