### ISSUE TITLE
fd_advise on stdin returns 0

### ISSUE THREAD

**Issue by yagehu** [wasmerio/wasmer#1702]
I wrote a short WebAssembly text format program that simply performs `fd_advise` on stdin. In other runtimes I've run this on (Wasmtime, WAVM, SSVM), the return code is 76 `notcapable`. But Wasmer returns 0 indicating success. I'm not sure if there's a standard behavior in this case. Thought I'd report this just in case.

```sh
$ wasmer -V                
wasmer 0.17.1
```

### Steps to reproduce

Run this program with just `wasmer run` without any flags.

```wat
(module
  (import "wasi_snapshot_preview1" "proc_exit"
    (func $__wasi_proc_exit (param i32))
  )
  (import "wasi_snapshot_preview1" "fd_advise"
    (func $__wasi_fd_advise (param i32 i64 i64 i32) (result i32))
  )

  (func $_start (export "_start")
    (local $err i32)

    (local.set $err
      (call $__wasi_fd_advise
        (i32.const 0)
        (i64.const 0)
        (i64.const 0)
        (i32.const 0)
      )
    )
    (if
      (i32.ne (local.get $err) (i32.const 0))
      (then (call $__wasi_proc_exit (local.get $err)))
    )

    (call $__wasi_proc_exit (i32.const 0))
  )

  (memory $memory (export "memory") 1)
)
```

### Expected behavior

The above program when run should return 76.

### Actual behavior

It returns 0.

**Comment by MarkMcCaskey** [comment]
Interesting, I'm not sure about stdin. It would make sense that it's not possible. I don't think the capabilities for any of the standard files is documented anywhere expect in the source code of WASI libc... `fd_advise` in Wasmer is currently a no-op because it's just a function for possibly optimizing file usage by giving hints about how the program wants to use it.  And it's always valid to just ignore these requests for optimization.

It would be good for someone to go through WASI libc and look at the default capabilities on `stdin`, `stdout` and `stderr` and update the code in Wasmer-wasi accordingly.

This is a very minor bug, but it's possible other incorrect capabilities on stdin and friends could be a bigger deal though.

**Comment by Amanieu** [comment]
In this case the behavior is indeed different between wasmer and wasmtime, but this is normal. As with #1703, WASI doesn't specify what rights are available on stdin/stdout/stderr so this is implementation-defined.
