### ISSUE TITLE
AOT compilation in C API

### ISSUE THREAD

**Issue by liamappelbe** [wasmerio/wasmer#1747]
In the old API it was possible to serialize a compiled module using `wasmer_module_serialize`. Is there an equivalent in the new API?

Also, what features do I need to use when building the wasmer-c-api crate to get a runtime that only supports running pre-compiled modules? I tried just removing "jit" and "cranelift" from my usual features, leaving only "wasi", but then I get compile errors. I'm interested in minimizing the size of the binary, and I assume the compiler is the largest component. The shared library is currently about 16MB and ideally I'd like to get it down to a few MB.

**Comment by liamappelbe** [comment]
As a quick check, I tried building an AOT only version of Wasmer by removing the "jit" and "cranelift" features, then just commenting out those compiler errors. This got the binary down to 5MB with WASI and 3.5MB without it. Would an approach like that work, or have I cut out something important?

**Comment by MarkMcCaskey** [comment]
That should work!  We intend to support Wasmer without a compiler in headless mode.  I believe you will need an engine to deserialize with, however!

Additionally, if you want smaller binaries there are some settings that can be tweaked.  Cargo has nightly support for custom named profiles and when that becomes stable we'll provide more specialized ways to build Wasmer.  However for now we're limited to a few default profiles and can't easily provide other ways to compile to users on stable.

But in case you're interested in trying that out earlier, you can add this to the Cargo.toml (you may have to actually add it to top level `Cargo.toml` because these settings can only be defined once per workspace):

```toml
[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'  
incremental = false
codegen-units = 1
```

Should significantly reduce the binary size as well at the cost of slower compilation and less information on crashes.

`panic = 'abort'` will remove support for panic unwinding which is probably fine for the C API because unwinding through an FFI boundary is currently undefined behavior in Rust. However the error messages may be worse if our Rust code panics.
`codegen-units=1` will also likely significantly reduce binary size by doing code generation on a single thread which allows LTO to be more aggressive.

Aside from that, there are a number of other ways to further reduce binary size, which are higher effort, that I'm aware of.  We likely won't prioritize that soon, but in the future it should be possible to make an AOT/headless version of Wasmer with a much, much smaller size!

**Comment by Hywan** [comment]
Since https://github.com/wasmerio/wasmer/pull/2118, there is the `wasmer_is_headless` function that allows to determine whether a compiler has been compiled with the current `libwasmer`. To compute `libwasmer` with a compiler, you at least need the `compiler` Cargo feature. Otherwise, no compiler will be installed.

The new API based on Wasm C API provides `wasm_module_serialize` and [`wasm_module_deserialize`](https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/module/fn.wasm_module_deserialize.html), see this later to get a fully working example.

Reminder: To define the engine to use, see [`wasm_config_set_engine`](https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/engine/fn.wasm_config_set_engine.html).

Reminder: To define the compiler to use, see [`wasm_config_set_compiler`](https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/engine/fn.wasm_config_set_compiler.html).
