### ISSUE TITLE
Rust/wasm interoperability

### ISSUE THREAD

**Issue by Yamakaky** [wasmerio/wasmer#1750]
### Summary

What is the current best practice for exchanging complex data between rust and wasm? There is wasm-bindgen, but it's very centered on JS interoperability.

One possibility is to have malloc/free on wasm side, maybe using Box::from/to_raw. You could then have an allocator rust-side that calls these functions and reuse buffers to limit costs. You then have a serializer like nanoserde to convert the data.

Ideally this would be documented to be runtime-independent, like using a C vm for example.

### Additional details

How I do it:

WASM function wrapper: https://github.com/Yamakaky/distilled/blob/master/src/lib.rs#L125-L141

WASM definitions: https://github.com/Yamakaky/distilled/blob/master/src/lib.rs#L24-L38

I uses a shared buffer for input and output, with one function to get the address from rust. The output buffer pointer + size is packed in a u64 as output of the wrapper. nanoserde is used to handle serialisation. For my use case, it's enough, but that's not very flexible.

**Comment by MarkMcCaskey** [comment]
@Yamakaky That's a good question, unfortunately there isn't a great answer yet.

Right now each ABI essentially does its own thing in regards to data exchange between the host and guest.  The WASI syscalls are very carefully designed to not have any need for higher level constructor and destructor functions at the cost of writing the syscalls in a very low level way.  For example, when listing the entries in a directory, rather than have the host have to allocate memory on the guest, it simply fills as much of the buffer given to it by the guest as it can and asks the guest to call it again for the next part.  This glue code is then usually included in the wasi-libc so users of WASI don't need to see it.

In the future with Wasm interface types, VMs will be able to generate code to pass higher level data back and forth, hiding the tedious and error-prone details from the users of the VM.

We have a few tools for helping with this data transfer, for example [WasmPtr](https://docs.rs/wasmer/1.0.0-alpha4/wasmer/struct.WasmPtr.html): though this API may need to be changed a bit to prevent unsound behavior in Rust (by for example holding a `&` into memory that then changes)...

We're open to including other helper functions in Wasmer or making changes to make user-supplied extensions easier, so if you have any ideas feel free to let us know!

I do think data transfer is probably the biggest blocker for users using custom ABIs as much as they should right now which is a bit unfortunate.
