### ISSUE TITLE
Can wasmer support async feature?

### ISSUE THREAD

**Issue by leenux** [wasmerio/wasmer#1918]
When the server uses wasmer to handle large concurrency, it will reduce the resource consumption

**Comment by syrusakbary** [comment]
Hi @leenux do you mean async in Wasmer Rust API, or do you mean an async I/O API in WASI?

In the first case, it would be super useful to have a code snippet on how you would like to use it!

**Comment by leenux** [comment]
@syrusakbary Yes, it is first case. Where are the code snippet plz?

**Comment by kaimast** [comment]
I'm somewhat interested in the latter case. There seem to be no easy way to start a wasmer instance inside and async rust function and then use async in any of the host functions.

The first case should already be possible right? You just would need to port something like tokio to run on wasm.

**Comment by MarkMcCaskey** [comment]
> @syrusakbary Yes, it is first case. Where are the code snippet plz?

I think he was asking for example pseudo-code of what an async Wasmer API would like / what in particular would be helpful for you if it was async.

I think we can definitely do it, there are a few issues we'd have to think through first though.  For example 1 issue I see with it is that either we have to fully convert to async or maintain 2 APIs. Fully converting to async shouldn't be much of a problem for us but it does have 1 downside in that it makes compiling headless Wasmer down to the smallest executable possible more difficult. I imagine even with an async runtime designed to be as small as possible, you'll still end up shipping more code overall than a binary with no async runtime at all.

Another big issue I can think of right now where async in our API might be difficult is the limitations around where you can define `async` functions.  For example, I think the inability to make trait methods `async` could be a major blocker towards making the Wasmer API async because we use traits in a lot of critical places to abstract out engine behavior and compiler behavior.  These types of limitations will be lifted in the (hopefully near) future though.

**Comment by leenux** [comment]
Temporary close this issue, expect to see asynchronous features as soon as possible
