### ISSUE TITLE
WasmPtr and Memory in 1.0.0

### ISSUE THREAD

**Issue by kaimast** [wasmerio/wasmer#1925]
Hi! 

I am trying to port my code from `wasm-runtime` to the `wasmer` crate. As far as I can tell `Ctx` has been removed.

[Here](https://docs.rs/wasmer/1.0.0-beta1/wasmer/struct.WasmPtr.html) it says you can pass memory as the first argument of a host function. However when I try to pass such a function to `Function::new_native` I get the following error:

```the trait `HostFunction<_, _, WithoutEnv, _>` is not implemented for `for<'r> fn(&'r wasmer::Memory, WasmPtr<u8, Array>, u32) {log_info}` ```

Any idea what I am doing wrong? I tried, both, passing memory by value and by reference. I also cannot find any examples on how to write a host function that takes a Ptr as an argument in the repository.

Thanks,
Kai

**Comment by webmaster128** [comment]
The example you are referring to is outdated. [Looking at the blame](https://github.com/wasmerio/wasmer/blame/master/lib/api/src/ptr.rs), it is pre-1.0 and not updated since then.

If you want to accedd memory from the host function, you need [Function::new_native_with_env](https://docs.rs/wasmer/1.0.0-beta1/wasmer/struct.Function.html#method.new_native_with_env) where `Env` a type defined by you that allows you to share things between functions. Your custom `Env` can implement `WasmerEnv`, which gives you are standardized way to access the memory via lazy loading: https://docs.rs/wasmer/1.0.0-beta1/wasmer/trait.WasmerEnv.html

**Comment by kaimast** [comment]
Thanks, that seems to work!
