### ISSUE TITLE
How to enable wasi imports

### ISSUE THREAD

**Issue by yowl** [wasmerio/wasmer#1977]
### Summary

I'm compiling and linking some llvm mixed with cpp using emscripten and wasm-ld, using emscripten's `-s STANDALONE_WASM` option so I can run it in wasmer.  What happens is
```
wasmer .\HelloWorld.wasm
error: failed to run `.\HelloWorld.wasm`
╰─> 1: Error while importing "wasi_snapshot_preview1"."fd_close": unknown import. Expected Function(FunctionType { params: [I32], results: [I32] })
```

### Additional details
I run wasm2wat to try to understand what is happening and the first import is for `fd_close`
```
  (type (;229;) (func (param i64 i64) (result f64)))
  (type (;230;) (func (param f64 f64 f64 f64) (result f64)))
  (import "wasi_snapshot_preview1" "fd_close" (func $__wasi_fd_close (type 1)))
  (import "env" "__sys_getdents64" (func $__syscall220 (type 5)))
  (import "env" "__sys_fadvise64_64" (func $__syscall272 (type 21)))
  (import "env" "__sys_prlimit64" (func $__syscall340 (type 7)))
  (import "env" "__sys_ugetrlimit" (func $__syscall191 (type 3)))
```
I'm probably just being a bit dense here, but doesn't wasmer provide the `wasi_snapshot_preview1` module ?

Provide any additional details here.

wasmer version

```
PS E:\GitHub\runtimelab\samples\HelloWorld\bin\wasm\Debug\net5.0\browser-wasm\native> wasmer --version
wasmer 1.0.0-beta2
```
On Windows as you can see.

**Comment by Hywan** [comment]
Hello,

Wasmer does provie WASI support for `wasi_snapshot_preview1`.
The default builds include have the `wasi` feature enabled by default.
Our WASI implementation works on Windows.

How did you install or compile Wasmer?

Can you share the `.wasm` module here please?

Thanks!

**Comment by yowl** [comment]
I compile some c++ with emscripten, `emcc -c`, and then I build some LLVM bitcode with libLLVM.  The bitcode is compiled to wasm also using emscripten, `emcc -c` and finally the wasm archives (from cpp) and wasm object file (from LLVM bitcode)  are linked together with emscripten with the `STANDALONE_WASM` flag:
```
emcc E:\GitHub\runtimelab\samples\HelloWorld\obj\wasm\Debug\net5.0\browser-wasm\native\HelloWorld.o -o E:\GitHub\runtimelab\samples\HelloWorld\bin\wasm\Debug\net5.0\browser-wasm\native\HelloWorld.wasm -s ALLOW_MEMORY_GROWTH=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 --emrun E:\tmp\runtimelabpkg\runtime.browser-wasm.microsoft.dotnet.ilcompiler.llvm\6.0.0-dev/sdk/libPortableRuntime.a E:\tmp\runtimelabpkg\runtime.browser-wasm.microsoft.dotnet.ilcompiler.llvm\6.0.0-dev/sdk/libbootstrapper.a E:\tmp\runtimelabpkg\runtime.browser-wasm.microsoft.dotnet.ilcompiler.llvm\6.0.0-dev/framework/libSystem.Native.a E:\tmp\runtimelabpkg\runtime.browser-wasm.microsoft.dotnet.ilcompiler.llvm\6.0.0-dev/framework/libSystem.Globalization.Native.a -s STANDALONE_WASM -s DISABLE_EXCEPTION_CATCHING=1 -s FORCE_FILESYSTEM=1 -g3
```

Wasm zip attached, thanks!
[HelloWorld.zip](https://github.com/wasmerio/wasmer/files/5770243/HelloWorld.zip)

**Comment by yowl** [comment]
I downloaded and installed  wasmer from powershell with
```
iwr https://win.wasmer.io -useb | iex
```
I did that again today, and now on
```
wasmer 1.0.0-rc1
```
Message the same:
```
PS E:\github\runtimelab\samples\HelloWorld\bin\wasm\Debug\net5.0\browser-wasm\native> wasmer .\HelloWorld.wasm
error: failed to run `.\HelloWorld.wasm`
╰─> 1: Error while importing "wasi_snapshot_preview1"."fd_close": unknown import. Expected Function(FunctionType { params: [I32], results: [I32] })
```

**Comment by MarkMcCaskey** [comment]
Currently Wasmer doesn't have great support for more recent versions of emscripten which mix WASI and emscripten calls, this is because it hasn't been a high priority for us and the design of the emscripten ABI is tightly coupled to the javascript it emits so it's hard to provide generic support for it without that generated JS... Last I checked there was no way for us to easily identify which version of emscripten a Wasm module was compiled with and due to all the changes between versions, we can never really have stable support (unless we always targeted the latest version or did some clever deduction based on what the module looks like (which we'd have to automate because it's a huge task) to figure out what version it was compiled with and provide proper support).

Additionally, simply exposing WASI imports directly likely would not work for us if emscripten expects the functions it's calling by WASI names to work with the other emscripten functions, which I assume it does.  The reason is that our WASI implementation maintains its own sandbox, and our emscripten implementation does not. So a file handle opened with an emscripten function cannot be closed with the WASI close function, for example.

Emscripten is a much larger ABI and is harder to sandbox, but it's certainly possible to do (it's done in the browser!), however that wasn't what we were focused on when building it and likely would be a much larger effort than WASI support in any case.

So ultimately, this is a solvable problem but it isn't a high priority for us right now. We'd be happy to accept changes modifying our emscripten implementation to be compatible with our WASI implementation though.

In the meantime, if your application works with plain `wasm32-wasi`, that's an easier ABI for server-side Wasm runtimes to implement and we're highly prioritizing WASI support right now, so you may have better luck. The one drawback is that WASI being much younger, focused on sandboxing, and simpler is that it's currently missing many common features such as native support for networking.

**Comment by yowl** [comment]
Thanks for the detailed reply.  I'm happy to at least try to go `wasm32-wasi`, and that seems like a logical diretion, so your last paragraph is of particular interest,  As I understand, and in simple cpp programs it appears to work, emscripten with the STANDALONE_WASM flag produces wasm files that do run in wasmer, e.g.
```
#include <stdio.h>

int main()
{
  printf("Hello\n");
}

```
And 
```
emcc 1.cpp -o 1.wasm -s STANDALONE_WASM=1
```
Gives
```
PS E:\github\runtimelab\samples\HelloWorld\bin\wasm\Debug\net5.0\browser-wasm\native> wasmer e:\tmp\1.wasm
Hello
```
All good.  This program does not use fd_close but does have
```
  (import "wasi_snapshot_preview1" "proc_exit" (func (;0;) (type 2)))
  (import "wasi_snapshot_preview1" "fd_write" (func (;1;) (type 14)))
```
My confusion is what I'm doing wrong that means that my import fails.  Is something happening in wasmer differently based on some analysis of the wasm?

**Comment by MarkMcCaskey** [comment]
Yeah, so this is arguably a bug in that we're giving unhelpful error messages here.

When the Wasmer CLI gets a Wasm binary, it inspects the imports and exports to see what type of module it is. For WASI, we're able to do a full and precise check because it has less than 50 imports, for Emscripten, we look at a few things that suggest that it's "probably an Emscripten module" and then only provide the Emscripten imports. If the Emscripten imports are insufficient for any reason (like the existence of WASI imports too), then you'll get the error message that you got.

This is a common enough occurrence that we should, at the very least, special case Emscripten module with WASI imports and provide a helpful error message.

**Comment by yowl** [comment]
Ah, so that is super useful.  Can you point me to the code that does this `probably an Emscripten module` decision?  Maybe I can remove some/all of the imports that it is checking.

Thanks.

**Comment by MarkMcCaskey** [comment]
https://github.com/wasmerio/wasmer/blob/master/lib/cli/src/commands/run.rs#L116

and

https://github.com/wasmerio/wasmer/blob/master/lib/emscripten/src/utils.rs#L13-L27

It's super simple, hacky code written a long time ago that's historically been "good enough". I was thinking about a project for a more general way of validating imports in the past allowing these things to work much better, but I never got around to really figuring out the hard parts of the design and implementing it

**Comment by yowl** [comment]
Great, thanks a lot for your time.

**Comment by yowl** [comment]
I wonder if I can come back to this.  I put a `println` into `is_emscripten_module` and it returns false but does not pick up the wasi imports, i.e. the message is 
```
error: failed to run `/mnt/e/github/runtimelab/samples/HelloWorld/bin/wasm/Debug/net5.0/browser-wasm/native/HelloWorld.wasm`
╰─> 1: Error while importing "wasi_snapshot_preview1"."fd_close": unknown import. Expected Function(FunctionType { params: [I32], results: [I32] })
```
This is coming from `resolve_imports` https://github.com/wasmerio/wasmer/blob/b4d2d8ee804a45850af2b3e012fdbbbdcb1185cb/lib/engine/src/resolver.rs#L138-L146.  I should check how the resolver is set up to go further, is that the right thing to do?

**Comment by MarkMcCaskey** [comment]
@yowl

In [that function](https://github.com/wasmerio/wasmer/blob/b4d2d8ee804a45850af2b3e012fdbbbdcb1185cb/lib/wasi/src/utils.rs#L45) there's a "strict" parameter which says whether to check if it's a WASI module or check if it's exclusively a WASI module. For the CLI, we check that it's exclusively a WASI module.

The line 

```Rust
 if imports.all(|module| module == first_module) { 
 ```
 
here is checking that they all have the same namespace because it's on the `strict` path. `strict` is important for executing from the CLI because we need to ensure the WASI module is well-formed and will just work, things that are not pure WASI won't work, so we have to exclude them.
 
In the example you posted above, it's not pure WASI so it won't be detected as a WASI module by the CLI.
 
We haven't implemented the later changes to Emscripten including using functions with WASI names. Our WASI implementation uses a sandboxed filesystem and our Emscripten implementation does not, so the functions are fundamentally incompatible and can't be used together. It's possible to make this work, but it's a lot of work and hasn't been high priority for us.

I think modern Emscripten is sufficiently different that even if the WASI imports resolved and Emscripten worked with our virtual filesystem, there'd still be a lot of work to do to update everything that's changed

**Comment by yowl** [comment]
Thanks, I'll work on making it pure WASI coming out of emscripten.. This https://github.com/emscripten-core/emscripten/pull/12704/files looks like it will help when it lands.
