### ISSUE TITLE
Is the 'static lifetime for `Env` in `Function::new_native_with_env()` necessary?

### ISSUE THREAD

**Issue by Jibbow** [wasmerio/wasmer#1978]
### Summary

The functions [`Function::new_native_with_env(...)`](https://github.com/wasmerio/wasmer/blob/19e1ca80ce59c154d9318e2f7279d8831f724a66/lib/api/src/externals/function.rs#L70) and [`build_export_function_metadata(...)`](https://github.com/wasmerio/wasmer/blob/19e1ca80ce59c154d9318e2f7279d8831f724a66/lib/api/src/externals/function.rs#L376) both require the `Env` parameter to have a static lifetime. The change was introduced in https://github.com/wasmerio/wasmer/commit/4494bea70ae29ca845e423e40e6756b11e6be713

I played around a bit and apparently the `'static` lifetime bound can just be removed and tests are still passing. However, I'm not sure if not having a `'static` lifetime bound somehow introduces undefined behavior because of the unsafe code blocks. Changes can be found here: https://github.com/Jibbow/wasmer/commit/8128214216c9faf8a1226ac766dfbdb99b884db8

### Additional details

I came across this issue when I tried implementing a custom WASM environment that contained a reference to an object.

**Comment by MarkMcCaskey** [comment]
Yes, the `'static' lifetime on `Env` is necessary because `Function`s (and their `Env`s) can live for an arbitrarily long period of time. Thus accepting anything less than `'static` would allow use after free bugs.  This is fairly hard to test, we may be able to make a test that uses a type that reads a mutable global variable in `Drop` and panics so we can assert it doesn't get dropped until the correct point in the program though

**Comment by Jibbow** [comment]
Nice, thanks for the quick answer! :)
