### ISSUE TITLE
Undefined behavior in `EmEnv::set_memory`

### ISSUE THREAD

**Issue by caelunshun** [wasmerio/wasmer#2122]
### Describe the bug

`EmEnv::set_memory` is implemented as:

```rust
pub fn set_memory(&mut self, memory: Memory) {
        let ptr = Arc::as_ptr(&self.memory) as *mut _;
        unsafe {
            *ptr = Some(memory);
        }
    }
```

There are two problems with this code:
* casting `*const Memory` to `*mut Memory` creates a mutable pointer from an immutable pointer, which is UB.
* the `Arc` could have been cloned and sent to another thread, in which case writing to `ptr` is a data race.

**Comment by Hywan** [comment]
Maybe we should use [`Arc::get_mut`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.get_mut) or `Arc::make_mut` in this case. Thoughts @MarkMcCaskey?

**Comment by protheory8** [comment]
How does one solve the second problem?

**Comment by MarkMcCaskey** [comment]
Now that we have derive support with https://docs.rs/wasmer/1.0.2/wasmer/trait.WasmerEnv.html , I believe this should be solvable with that. It'll just take refactoring some code to make it work. If the memory is imported and not exported from Emscripten then it may be a bit more work because the `WasmerEnv` derive macro doesn't support grabbing imports yet.

I don't think there's an easy solution though; the current behavior is a consequence of the way the code was structured previously and an attempt to avoid spending too much time on it. I'd be surprised if there's a solution that doesn't involve rewriting a decent chunk of `emscripten/lib.rs`.

I can take a quick look again and see if there's a straight-forward solution that I missed, but otherwise, I probably won't be able to prioritize this for a while.
