### ISSUE TITLE
Upload C or C++ source code for guest modules in your examples

### ISSUE THREAD

**Issue by diceangel20** [wasmerio/wasmer#2129]
Hi,

Could you upload source code for guest modules in your examples here:
https://github.com/wasmerio/wasmer/tree/master/lib/c-api/examples

Thank you in advance.

**Comment by Hywan** [comment]
Hello,

What example are you talking about exactly please :-)?

**Comment by diceangel20** [comment]
Hello Hywan,

Sorry for that, I meant about this part:
`const char *wat_string =
        "(module\n"
        "   (type $mem_size_t (func (result i32)))\n"
        "   (type $get_at_t (func (param i32) (result i32)))\n"
        "   (type $set_at_t (func (param i32) (param i32)))\n"
        "   (memory $mem 1)\n"
        "   (func $get_at (type $get_at_t) (param $idx i32) (result i32)\n"
        "     (i32.load (local.get $idx)))\n"
        "   (func $set_at (type $set_at_t) (param $idx i32) (param $val i32)\n"
        "     (i32.store (local.get $idx) (local.get $val)))\n"
        "   (func $mem_size (type $mem_size_t) (result i32)\n"
        "     (memory.size))\n"
        "   (export \"get_at\" (func $get_at))\n"
        "   (export \"set_at\" (func $set_at))\n"
        "   (export \"mem_size\" (func $mem_size))\n"
        "   (export \"memory\" (memory $mem)))";`

Could you provide this part of guest module in a C or C++ code? We want to see the syntax on how to create them in C/C++. Tried wat2wasm and wasm2c but we believe that this way made it looks more complicated than what it should be.

Thank you.

**Comment by MarkMcCaskey** [comment]
Following up on this, I think we probably don't want to have C source code (or any other language for that matter) for all the WAT we use for tests because we use a _lot_ of WAT for tests and the WAT is more direct for showing what's happening in the WebAssembly itself than source code is. However I think it would be very useful to have docs or links to docs about how to do all the WebAssembly things from a given language as some things are really not obvious.

This project of documenting how to precisely use Wasm from various languages is honestly even a bit out of scope for Wasmer but I think this kind of info would be super valuable to the community. If anyone reading this is interested in collaborating on this, reach out to us!

**Comment by diceangel20** [comment]
Let us know where to start with. We maybe able to do something. Any link, document for knowledge needs to acquire?

**Comment by Hywan** [comment]
Taking the example of:

```
(func $get_at (type $get_at_t) (param $idx i32) (result i32)
    (i32.load (local.get $idx)))
```

If it was a host function, you should need to process like this:

* Create an environment, as a struct, something like: 

    ```c
    typedef struct {
        wasm_memory_t* memory;
    } my_env;
    ```

* Initialize the environment,
* Create the host function with [`wasm_func_new_with_env`](https://docs.rs/wasmer-c-api/1.0.2/wasmer_c_api/wasm_c_api/externals/fn.wasm_func_new_with_env.html)
* Then instantiate the module,
* Finally, read the exported memory, and map it to the `my_env.memory` field.

That way, your host function can read from the memory.

However, I don't know exactly how to produce this exact Wasm code from C directly. It depends —of course— of the compiler being used. `get_at` might probably be something like:

```c
int32_t* get_int_at(address: int32_t) {
    return (int32_t*) address;
}
```

I don't the equivalent of `memory.size` in C though, sorry.

**Comment by diceangel20** [comment]
It gave us an idea on how it should be done. Thank you.
