### ISSUE TITLE
Security model

### ISSUE THREAD

**Issue by tjpalmer** [wasmerio/wasmer#221]
Hello. I was wondering if you intend to support sandboxing and some kind of security model. If it's in the readme or other documentation, I apologize for missing it.

**Comment by lachlansneff** [comment]
Thanks for asking!

By design, webassembly is sandboxed by default. Aside from that, any sandboxing is really on the interface that's imported into your webassembly modules.

Our current emscripten implementation is not sandboxed whatsoever, but a strict security model is on our roadmap for future wasm abi implementations.

**Comment by tjpalmer** [comment]
Sounds good. Since your [home page](https://wasmer.io/) shows starting a web server, I presumed that meant you had built in certain capabilities already. So I figured it was worth asking. Glad to hear it's in the plans. Maybe this or else more precise issues are worth keeping open until you have plans implemented and/or documented.

**Comment by alexeypetrushin** [comment]
> By design, webassembly is sandboxed by default

Is it possible to set CPU cycle limit and Memory limit?

**Comment by Hywan** [comment]
It is possible to limit the memory size, yes. But it's not possible to limit the CPU frequency. I think it falls to the OS to slow down the Wasmer runtime process. I don't know yet how to do that though.

**Comment by alexeypetrushin** [comment]
Thank you! Is it possible to limit the execution time (roughly, with precision like +-100milliseconds for example)?

**Comment by bjfish** [comment]
@alexeypetrushin It’s on our roadmap to provide metering of memory/cpu instructions and preemption based on those values and possibly timeouts.

**Comment by webmaster128** [comment]
> It is possible to limit the memory size, yes. 

How would you do that? I don't see and interface for that in [wasmer_runtime::Module::instantiate](https://docs.rs/wasmer-runtime/0.16.2/wasmer_runtime/struct.Module.html#method.instantiate)?

In my tests, some Wasm was able to allocate 2x2 GB before hitting some kind of default limit.

**Comment by coolreader18** [comment]
I'm looking into adding an execution timeout middleware, what do you think the best way to go about it would be? My current plan would be to just implicitly depend on a wasi `clock_time_get` import and compare that value with some preset one, but are there any other ways to monitor time in wasm/wasmer without depending on imports?

**Comment by jcaesar** [comment]
* Instead of limiting execution time, wasmer can limit the number of instructions executed: [metering.rs](https://github.com/wasmerio/wasmer/blob/ec36089cbf4a65b768501ba38f3d63baad6badf3/examples/metering.rs).
* 2×2GB is probably simply the limit addressable in 32 bit wasm? A lower limit can be set through [tunables](https://github.com/wasmerio/wasmer/blob/ec36089cbf4a65b768501ba38f3d63baad6badf3/examples/tunables_limit_memory.rs).

**Comment by Hywan** [comment]
@al6x, @webmaster128:

> As for the memory limit - can you please point me to docs or info how to specify it?

https://github.com/wasmerio/wasmer/blob/ec36089cbf4a65b768501ba38f3d63baad6badf3/examples/tunables_limit_memory.rs

**Comment by Hywan** [comment]
@coolreader18 I think it's a good idea to start with something simple, even based on the host clock. I'll let you open an issue or a PR to track your progression and the discussion :-).

**Comment by syrusakbary** [comment]
Small update. Wasmer is fully sandboxed when used with WASI
