### ISSUE TITLE
Reference Types proposal support

### ISSUE THREAD

**Issue by protheory8** [wasmerio/wasmer#2222]
### Motivation

[Reference Types proposal](https://github.com/WebAssembly/reference-types) have been recently moved into the [Finished Proposals list](https://github.com/WebAssembly/proposals/blob/master/finished-proposals.md) and it seems to be a rather important proposal to implement.

**Comment by MarkMcCaskey** [comment]
Thanks for filing an issue for this.; we actually have a PR open to add the bulk of the feature to Wasmer in #2092 which we'll be merging upstream soon. The core of the reftypes proposal is implemented, but there are 2 missing pieces that impact it at the Wasmer API level.

The first is about the ergonomics of passing and returning `Function` objects due to the way things currently work (there may be a relatively direct fix for this but we're discussing some of our core data storage before making changes here).

The second is about reference counting externrefs in edge cases, specifically decrementing the reference count of things on the stack while unwinding in the generated code in the case of a trap. We've designed a few solutions but it's tricky given that we have 3 different compilers with different trade-offs and all the solutions had drawbacks that could limit other features in the future (for example stack-switching).

The state of the PR right now and probably how it'll be iin our next release is that there will be a compile time feature flag to enable `ExternRef`s at the API level because they leak memory in various cases (for example when there's a trap in Wasm code). Funcrefs (`Function`) work in a number of situations but not in all of them and all the failure modes are well-defined (so it may panic when used in certain ways, but when it doesn't panic, it should work completely correctly). We'll then follow up to finish these features over time.

If you're interested in working on solving some of these remaining hard problems with us, we'd be happy to hear some fresh ideas here.

**Comment by protheory8** [comment]
Unfortunately I don't really know much about Wasmer internals, so I'm not sure if I could help.

**Comment by syrusakbary** [comment]
Closing the issue as Reference Types is already supported in Wasmer in `master` (since wasmer 2.0)
