### ISSUE TITLE
Explain difference vs. wasmtime

### ISSUE THREAD

**Issue by sandstrom** [wasmerio/wasmer#2259]
Great if your documentation and/or website could explain how this project (features, goals, etc) differs from wasmtime.

Maybe something in the spirit of Hashicorps "Our product X vs. other software":

https://www.consul.io/docs/intro/vs
https://www.terraform.io/intro/vs

**Comment by dsherret** [comment]
See https://wasmer.io/wasmer-vs-wasmtime

**Comment by syrusakbary** [comment]
Thanks for creating the issue @sandstrom.
On the page that David posted we showcase the main differences between the runtimes. Wasmtime is a great runtime and you will be completely fine in the long term if you end choosing them.

Regarding features and goals, I think we differ on long-term vision and approach. For example, the team behind wasmtime is leading the experimentation into module-linking while we try to remain a bit more pragmatic on the features we support.

On the technical side for us speed, performance, and API reliability are critical (we are very careful when designing our API to minimize breaking changes). On the non-technical side, we try to empower our community as much as is in our hands.

Since I can't speak for wasmtime on what are their goals I think it might be easier for you to ask them directly. Closing the issue here, but I'll be super happy to answer any questions you may have about Wasmer!

> That said, where are the benchmarks for this?

We are working on publishing a full set of benchmarks soon @dsherret. We are a bit behind schedule on this one!

**Comment by sandstrom** [comment]
@dsherret @syrusakbary Thanks, totally missed that page! (even knowing the URL I can't find link from the home page root though) Great summary, exactly what I had in mind. You're one step ahead.
