### ISSUE TITLE
Wasmer's Emscripten host functions may be unsound due to calls to `getenv`

### ISSUE THREAD

**Issue by xerxes12354** [wasmerio/wasmer#2267]
I was looking at the time crate wondering why the [time crate didn't give offsets](https://github.com/time-rs/time/issues/293), and I stumbled upon [this thread on Internals](https://internals.rust-lang.org/t/function-to-hold-lock-on-execution-environment-for-ffi/13702/22). This seems like a big problem so I went looking for FFI crates where this could be a problem.

Looking at wasmer source code, [and the code calling getenv here](https://github.com/wasmerio/wasmer/blob/1b0c87034708e22adbfdd3725b25bf1810a21479/lib/emscripten/src/env/unix/mod.rs#L3), it looks like  this wrapper has a data race when `set_env` is called in another thread.

**Comment by MarkMcCaskey** [comment]
Thanks for the bug report!

There are actually a few other issues in the code you linked to too:

1. We're passing a pointer to part of Wasm linear memory into a libc function, nothing is preventing the memory being pointed to from being mutated during this process.
2. There's no guarantee that the memory being passed to this function has a nul-terminator. From the docs, Rust is currently calculating the length up front, so that could presumably access off the end of the Wasm heap (which should trigger a fault resulting in a Wasm trap) if there are no 0 bytes after the pointer. But Rust may not always calculate the length up front which means this trap could also occur in the libc call.

Additionally, many Wasm ABIs (maybe all?) use a Wasm global as the stack pointer to the C/Rust/Language-X stack. The reason is that the Wasm stack itself lives outside of memory, so you can't take a reference to anything on the stack. This obviously can't work for languages like C and Rust, so the compiler generates code to maintain two stacks: the Wasm stack and the in-Wasm-linear-memory stack used for local variables that need to have an address. Thus calling into 2 different Wasm functions concurrently will lead to Wasm internal corruption in many cases if that trick is used. We'd need thread-local Wasm global variables to make that stack pointer trick work.

That said corruption in the host is much worse than corruption in the Wasm, so an explicit nul-check followed by either locking that part of Wasm linear memory or copying that data out as well as maintaining a lock on syscalls like this does seem necessary.
