### ISSUE TITLE
Host Memory In Wasm (Follow on to #2273)

### ISSUE THREAD

**Issue by dbcfd** [wasmerio/wasmer#2284]
### Summary

This is a follow on question to #2273. Using the approach of exposing host memory

```rust
    let import_object = imports! {
        "env" => {
            "host_memory" => m // or whatever is the imported name for that memory
        }
    };
    let instance = Instance::new(&module, &import_object)?;
```

we run into the following issues when attempting to use it with wasm32-wasi
* `fn host_memory() -> Memory` - Not ffi safe, requires bringing in wasmer which doesn't compile on wasm32-wasi
* `fn host_memory() -> *const Memory` - Not ffi safe, requires bringing in wasmer which doesn't compile on wasm32-wasi
* `fn host_memory() -> *const u8` - Results in `Instantiation(Link(Import("env", "host_memory", IncompatibleType(Function(FunctionType { params: [], results: [I32] }), Memory(MemoryType { minimum: 1 pages, maximum: None, shared: false })))))`
* `fn host_memory() -> i32` - Results in `Instantiation(Link(Import("env", "host_memory", IncompatibleType(Function(FunctionType { params: [], results: [I32] }), Memory(MemoryType { minimum: 1 pages, maximum: None, shared: false })))))`

What is the correct way to use the host memory in wasm?

**Comment by Hywan** [comment]
Hello,

You should first instantiate a memory, and then import it, as follows (pseudo-Rustish-code):

```rs
let memory = Memory::new(&store, MemoryType::new(1, None, false)).unwrap();

let import_object = imports! {
    "env" => {
        "host_memory" => memory,
    }
};
```

No need to create a function to create the memory.

All “entities” that can be used as export or import are implementing [the `Exportable` trait](https://docs.rs/wasmer/1.0.2/wasmer/trait.Exportable.html). It is implemented for `Function`, `Global`, `Memory` or `Table`.

I hope I'm answering your questions :-).

**Comment by dbcfd** [comment]
> Hello,
> 
> Sorry if #2273 wasn't clear!
> You should first instantiate a memory, and then import it, as follows (pseudo-Rustish-code):
> 
> ```rust
> let memory = Memory::new(&store, MemoryType::new(1, None, false)).unwrap();
> 
> let import_object = imports! {
>     "env" => {
>         "host_memory" => memory,
>     }
> };
> ```
> 
> No need to create a function to create the memory.
> 
> All “entities” that can be used as export or import are implementing [the `Exportable` trait](https://docs.rs/wasmer/1.0.2/wasmer/trait.Exportable.html). It is implemented for `Function`, `Global`, `Memory` or `Table`.
> 
> I hope I'm answering your questions :-).

I'm not sure how to actually use that in my WASM module though. The methods I've tried above don't work, mostly around the wasmer engine expecting the function to be of type `Memory` which isn't usable in WASM.

**Comment by MarkMcCaskey** [comment]
> I'm not sure how to actually use that in my WASM module though. The methods I've tried above don't work, mostly around the wasmer engine expecting the function to be of type Memory which isn't usable in WASM.

If I'm understanding your question, it sounds like perhaps you're misunderstanding how Wasm memory works. The Wasm code doesn't have to do anything to access memory, if you use `Box::new` in Rust compiled to Wasm, you're using Wasm memory. So the Wasm guest can just use memory as it normally would and the semantics of accessing memory is all taken of for you.

You should never need to pass a host pointer to the guest: it's just a number as far as the Wasm guest is concerned because of the way Wasm is sandboxed

**Comment by dbcfd** [comment]
> > I'm not sure how to actually use that in my WASM module though. The methods I've tried above don't work, mostly around the wasmer engine expecting the function to be of type Memory which isn't usable in WASM.
> 
> If I'm understanding your question, it sounds like perhaps you're misunderstanding how Wasm memory works. The Wasm code doesn't have to do anything to access memory, if you use `Box::new` in Rust compiled to Wasm, you're using Wasm memory. So the Wasm guest can just use memory as it normally would and the semantics of accessing memory is all taken of for you.
> 
> You should never need to pass a host pointer to the guest: it's just a number as far as the Wasm guest is concerned because of the way Wasm is sandboxed

That's where the original question came from. The docs have this 

```
A memory created by the host or in WebAssembly code will be accessible and mutable from both host and WebAssembly.
```

The code in this thread creates host memory, which according to the docs, should be accessible from WebAssembly. How then do you access that memory? This memory seems like it should be different than the module's memory, which is readable/writable as Wasm memory.

**Comment by MarkMcCaskey** [comment]
To clarify some terms:

- "Host memory" - memory that belongs to the host running the VM. Technically all Wasm Linear Memory must live inside host memory but we generally refer to "host memory" in contrast to Wasm Linear Memory.
- "Wasm Linear Memory" - memory that Wasm can access as per the Wasm spec. Wasm Linear Memory can be imported or exported by a given Wasm module. Imported Wasm Linear Memory must be created by the host. Exported Wasm Linear Memory can be thought of as being created by the Wasm during instantiation. This is the `wasmer::Memory` type.

Wasm cannot access host memory under any circumstances, it can only access Wasm Linear Memory.

----

> we run into the following issues when attempting to use it with wasm32-wasi

`wasm32-wasi` uses exported memory in all cases that I'm aware of, so you won't be able to import memory into a WASI module unless you've specifically linked or compiled it in a non-standard way: this is a valid thing to do, I'm just not personally familiar with all the details here.

Given that the modules we're dealing with will already have a Wasm Linear Memory that they're exporting, I don't believe it's currently possible (at least not without using some experimental features) to have a Wasm module access multiple linear memories. I believe this will be possible in the future as it's a big feature of Wasm. The issue is that it's nice to compile existing code into Wasm and existing code doesn't have the notion of multiple separate memory spaces... So many cases of using multiple memories will be taken care of during compilation for you. There will likely also be ways to do it manually but it's not currently possible with the current Wasm spec as I understand it.

----

So with all that background knowledge out there, the answer is:

If the module is expecting an imported memory, simply instantiating it with a memory in the import object will make it use the memory. If the module is not, then there is no way to make the Wasm use that memory without modifying the Wasm or generating the Wasm to want to use it. (as far as I'm aware the change needed to the Wasm module to go from exported to imported should actually be very simple, just remove the export statement and add an import statement)

**Comment by dbcfd** [comment]
> Given that the modules we're dealing with will already have a Wasm Linear Memory that they're exporting, I don't believe it's currently possible (at least not without using some experimental features) to have a Wasm module access multiple linear memories. I believe this will be possible in the future as it's a big feature of Wasm. 
> So with all that background knowledge out there, the answer is:
> 
> If the module is expecting an imported memory, simply instantiating it with a memory in the import object will make it use the memory. If the module is not, then there is no way to make the Wasm use that memory without modifying the Wasm or generating the Wasm to want to use it. (as far as I'm aware the change needed to the Wasm module to go from exported to imported should actually be very simple, just remove the export statement and add an import statement)

That's what it felt like when testing, but the docs made it seem like it was able to create a second linear space that was then accessible (somehow). The missing part for me was that it specifically had to be the wasm memory type, and like you said, I'm not sure if that is easily possible currently in a rust wasm module.

Thank you for the explanation. Really felt like I was missing something from the docs.

**Comment by MarkMcCaskey** [comment]
> Thank you for the explanation. Really felt like I was missing something from the docs.

Glad I could help! Thanks for the heads up, I'm sure the docs do need to be updated to be more clear here
