### ISSUE TITLE
Document passing Env better

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#2294]
It's not super clear from the rustdocs of `wasmer` how to use `WasmerEnv`. It's something so basic we forgot to really show it, `Function::new_native_with_env` should probably be updated as well as `WasmerEnv` itself and maybe even the front page of the docs or something

**Comment by tzemanovic** [comment]
I'd like to suggest an improvements for the `Function` docs.

For the `new` and `new_with_env` constructors, it is apparent from their signatures that the wrapped functions should return `Result<Vec<Val>, RuntimeError>`.

However, for `new_native` and `new_native_with_env` it's not apparent what signature they can use because they use the `trait HostFunction` and its docs page doesn't show any implementations. It would be nice to document that these can either return any `WasmTypeList` and also `Result<impl WasmTypeList, RuntimeError>`.

**Comment by Hywan** [comment]
> However, for `new_native` and `new_native_with_env` it's not apparent what signature they can use because they use the `trait HostFunction` and its docs page doesn't show any implementations. It would be nice to document that these can either return any `WasmTypeList` and also `Result<impl WasmTypeList, RuntimeError>`.

Yeah. This feature is provided by the `IntoResult` trait, https://github.com/wasmerio/wasmer/blob/d292c24254a918de8c84c012a847ed815e0549dc/lib/api/src/externals/function.rs#L1016-L1030. It's used internally, so it's not obvious, you're right.

We are going to document that!
