### ISSUE TITLE
LazyInit<Memory> does not call munmap

### ISSUE THREAD

**Issue by kaimast** [wasmerio/wasmer#2304]
### Describe the bug
I noticed that when a host function's environment has a `LazyInit<Memory> `as a member, the exported memory is not cleaned up properly.

I dug through the Wasmer code last night but could not figure out what was causing this. Probably when resolving imports the Environment is cloned and then not destroyed, which keeps a dangling reference to the Memory.

(This code is really hard to read as it passed around a raw pointer to the environment and a bunch of function pointers to clone and drop it. Might be worth investigating if this could be done in a nicer way.)

### Steps to reproduce
You can checkout my branch and run the modified example.

```
git clone git@github.com:kaimast/wasmer.git
cd wasmer
git checkout lazy-init
cargo run --example imported-function-env --features=cranelift
```

This will instantiate a module and call a function 10000 times sequentially. Run `htop` (or similar) and observe the virtual memory usage of the program.

### Expected behavior
All memory should be unmapped after an instance is dropped.

### Actual behavior
On my system this simple example reserves 25 Terabytes in memory... and a process can run out of virtual memory in a few minutes.

**Comment by kaimast** [comment]
I did a git bisect and it seems like [this](
https://github.com/wasmerio/wasmer/commit/165152ddb81befb6181f533a53505b9001038278) commit by @syrusakbary introduced the issue.

**Comment by syrusakbary** [comment]
Thanks for pointing at the exact commit @kaimast, it will be useful when debugging!
I think the commit likely uncovered the bug, as the behavior introduced by the commit should be the correct one.

**Comment by kaimast** [comment]
Thanks! Do you think you will have time to take a look?

I can probably do it but I am not super familiar with the codebase...

**Comment by MarkMcCaskey** [comment]
Thanks, this is very, very useful information! I had just started looking into an independent user report related to this.

I think the issue here is that now exported `Memory` in `WasmerEnv` is keeping the `Instance` alive and the `Instance` itself is keeping the `WasmerEnv` alive, which means nothing gets freed anymore when using `WasmerEnv` with anything exported.

I believe Syrus is correct that locally this change is actually fixing a bug which in turn exposes an underlying bug in this case. I'll look into it but I think we should be able to come up with a fairly direct solution here.


As for simplifying the code, I'm not sure how much can be done, perhaps using more types with better names with documentation (specifically for our v-table thing going on here) could be very helpful, but due to our crate structure causing us to not be able to refer to a few critical types by name, some of this code gets a bit hairy. I'd love to hear any suggestions for how to improve it though because I agree that this is probably one of the most confusing things in all of the wasmer code base right now.
