### ISSUE TITLE
Cannot run go compiled wasm in wasmer

### ISSUE THREAD

**Issue by stewartie4** [wasmerio/wasmer#2311]
Running go hello world wasm in the browser works completely fine.
Running the same wasm via wasmer results in
![image](https://user-images.githubusercontent.com/18306778/118179541-57882400-b42d-11eb-831b-cc73fcbbc361.png)
any ideas?

**Comment by FGasper** [comment]
wasmer is failing because you’re not passing in the imports that that WASM code expects.

Do `wasm inspect hello-world.wasm` to see what all you need to pass in. TBH I don’t know if wasmer’s standalone executable allows you to set imports. You can definitely do it if you call wasmer programmatically though.

Basically, you have to implement `wasm_exec.js` in whatever non-JS context from which you run `hello-world.wasm`.

**Comment by Hywan** [comment]
Hello,

For what I understand from this error, I suspect you've compiled your Wasm module from a Go program. See this excellent comment from `wasmer-go` to learn how to use `tinygo` to generate Wasm module from Go that aren't tied to JS only, https://github.com/wasmerio/wasmer-go/issues/248#issuecomment-814685603.

As @FGasper said, Wasmer doesn't support the Go ABI as it's unstable yet, so it's best for you to (i) use TinyGo to get a clean Wasm module, or (ii) use Wasmer programatically (either with Wasmer, or its numerous embeddings).

I'm closing the issue unless you've another question :-).

**Comment by stewartie4** [comment]
@Hywan I tried using the wasmer java embed but got the same error as above but maybe @FGasper's suggestion is something I need to look into.
Thanks both for the help I will look into the above suggestions
