### ISSUE TITLE
WASI hostcalls do not set errno

### ISSUE THREAD

**Issue by emugnier** [wasmerio/wasmer#2410]
### Describe the bug

Inconsistent set/usage of  `errno` on errored WASI function calls. Errno is set in some cases but not others.

This behavior is seen on many WASI calls including but not limited to:

* `__wasi_fd_close`
* `__wasi_fd_allocate`
* `__wasi_fd_prestat_get`
* `__wasi_fd_fdstat_set_rights`
* `__wasi_environ_get`
* `__wasi_environ_sizes_get`

Example 1:

```c
// main.c

#include "stdio.h"
#include "errno.h"

int main()
{
    uint32_t fd = 1234;
    __wasi_fd_close(fd);
    printf("%d\n", __wasi_fd_close(fd)); // 8
    printf("%d\n", errno);               // 0

    return 0;
}

```

### Steps to reproduce

1. Copy `main.c` above.
2. Compile `main.c` using:

```bash
docker run \
  --rm \
  -v $(pwd):$(pwd) \
  wasienv/wasienv \
  wasicc `pwd`/main.c -o `pwd`/main.wasm
```

3. Run `wasmer main.wasm`

### Expected behavior

```
$ wasmer main.wasm
8
8
```

### Actual behavior

```
$ wasmer main.wasm
8
0
```

The second number is `errno` and should be set to `8` corresponding to "Bad file descriptor".

### Additional context

wasmer => 1.0.2

**Comment by emugnier** [comment]
I think you're right, after calling the raw syscalls errno is never set. If I read your comment correctly, it seems Wasmer is unable to set errno?
> ... the host side never directly sets errno (it has no knowledge of it).

I noticed that Wasmtime does indeed set this errno value. I'm wondering why Wasmer does not set it other than it's not part of the wasi spec?
I believe it would be generally good to set errno, as it's typically set with Linux system calls.

**Comment by MarkMcCaskey** [comment]
That's correct, errno is not part of the spec as far as I'm aware and would be an arbitrary global variable (memory address) that the VM  wouldn't know. I'd be curious to know how they're determining where the errno value lives.

Yeah, it's not that a VM couldn't access errno, it's just that it wouldn't know where it was without being told.

**Comment by Hywan** [comment]
@MarkMcCaskey 

>  I'd be curious to know how they're determining where the errno value lives.

Answering with my current knowledge. There is a special function in the “standard libc” that points to the `errno` location, under the name `__error`. [See the `intro(2)` documentation](https://www.freebsd.org/cgi/man.cgi?query=intro&apropos=0&sektion=2&manpath=FreeBSD+13.0-RELEASE+and+Ports&arch=default&format=html):

> Nearly all of the system calls provide an error number referenced via the
> external identifier `errno`.  This identifier is defined in `<sys/errno.h>`
> as
> 
> ```c
> extern int * __error();
> #define errno (* __error())
> ```
> 
> The `__error()` function returns a pointer to a field in the thread spe-
> cific structure for threads other than the initial thread.  For the ini-
> tial thread and non-threaded processes, `__error()` returns a pointer to a
> global errno variable that is compatible with the previous definition.

In the Rust `libc` crate, it's given by [the `__errno_location` function](https://docs.rs/libc/0.2.98/libc/fn.__errno_location.html).

I'm closing this issue since WASI is not designed to update `errno`. All functions in WASI return an error code of type `__wasi_errno_t`, to fulfill this exact purpose of not using `errno` (which is “specific”/tied to C).
