### ISSUE TITLE
CLI args in run subcommand: wasm module can't follow `--dir` or `--mapdir` with no `=`

### ISSUE THREAD

**Issue by caspervonb** [wasmerio/wasmer#2445]
### Describe the bug

`<FILE>` has to be first for options to work.

```sh
wasmer 2.0.0 | rustc 1.52.1 (9bc8c42bb 2021-05-09) | x86_64
```

### Steps to reproduce

```sh
wasmer run --dir foo bar.wasm
```

### Expected behavior

Program runs with the given directory

### Actual behavior

The `<FILE>` is interpreted as another directory.

```
error: The following required arguments were not provided:
    <FILE>

USAGE:
    wasmer run <FILE> <--dir <DIR>...>
```

**Comment by MarkMcCaskey** [comment]
Thanks for the report! I think this is specific to `--dir` and maybe `--mapdir` because they allow you to specify an arbitrary number of arguments. I would _not_ expect this to be the case for any other flags though

**Comment by Hywan** [comment]
Alternatively, we can use `wasmer run --dir <dir> -- <module.wasm>`.

I'm not sure we can do something about this. We are using [`structopt`](https://github.com/TeXitoi/structopt) under the hood, and I'm pretty sure it's an expected behavior in this case.

I'm in favor of considering this as a non-bug. What do you think?
