### ISSUE TITLE
How to both import wasi and host function in the C API?

### ISSUE THREAD

**Issue by shingfeel** [wasmerio/wasmer#2450]
### Summary

wasm-c-api
wasmer version: 2.0.0

Hi, I want to instantiate with both  wasi import and native function type import,  for example as screenshot:
![image](https://user-images.githubusercontent.com/87051506/124691739-e6d22500-df0e-11eb-96ea-506a47b994fa.png)

But，when i use "wasi_get_imports" to import function, compiler report error as:
    error:Failed to resolve import "" "host_function"
It seems wasi doesn't recognize host function import type.
So i decided to use "wasm_module_imports" to get all importtypes,  then use "wasi_get_unordered_imports" to get wasi importtype as wasm_extern_t  to import . however that still fails with error:
     "error:host env initialization error: missing export memory"

How can i import both wasi and host function? I know, wasmer-v1.x.x has "wasmer_module_import_instantiate" to  merge mul import, but it has deprecated in wasmer-v2.x.x.
I found same issue: https://github.com/wasmerio/wasmer/issues/2100. but it seems no fixed in wasm-c-api？

### Additional details

Provide any additional details here.

**Comment by Hywan** [comment]
Hello,

With the Rust API, you should do something like this:

```rs
let mut wasi_env = WasiState::new("my-program").finalize()?;
let mut import_object = wasi_env.import_object(&module)?;

// at this point, you've an ImportObject that contains all the
// declarations for WASI.

import_object.register("other_namespace", namespace);
```

The `ImportObject` API is nice because you don't need to think about “import indices”. Indeed, imports have a specific order, and the module name (aka namespace name) and import name is only a “high-level” concept. When passing the imports with the module for instantiation, the imports have no module name nor import name, it's just an array where the import position is key.

With [the standard Wasm C API](https://github.com/WebAssembly/wasm-c-api), there is no equivalent of the `ImportObject` API. You unfortunately need to manipulate an array of `wasm_extern_vec_t` by hand, which is really awful to do. Moreover, there is no standard API for WASI. Wasmer provides [the `wasi_get_imports` function](https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/wasi/fn.wasi_get_imports.html). There is also [the `wasi_get_unordered_imports` unstable non-standard function](https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/unstable/wasi/fn.wasi_get_unordered_imports.html) which manipulates a `wasmer_named_extern_vec_t`, precisely to facilitate this.

Here is how we proceed in [`wasmer-go`](https://github.com/wasmerio/wasmer-go/) (which uses the `wasmer-c-api`).

[In `wasi.go`](https://github.com/wasmerio/wasmer-go/blob/811a01387c712b45c9babf0e8b8ff315e18939f4/wasmer/wasi.go):

1. Use the `wasi_config_new`, `wasi_config_arg`, `wasi_config_env`, `wasi_config_mapdir` etc. function to build and to configure the equivalent of `WasiStateBuilder`,
2. Use the `wasi_env_new` function to build the equivalent of `WasiEnv`,
3. Use `wasi_get_unordered_imports` to get a `wasmer_named_extern_vec_t` array, it's like `wasm_extern_vec_t` except that all externs are associated to a pair module name + extern name,
4. We use this `wasi_get_unordered_imports` to build an `ImportObject` ourselves.

Later, [in `import_object.go`](https://github.com/wasmerio/wasmer-go/blob/811a01387c712b45c9babf0e8b8ff315e18939f4/wasmer/import_object.go), in `intoInner` where we generate a `wasm_extern_vec_t`:

4. Given a `wasm_module_t`, we iterate over all the import signatures with `wasm_module_imports`,
5. For each import signatures, we use `wasm_importtype_module` and `wasm_importtype_name` to get their respective module name and import name. Based on this information, we fetch the associated extern/import (if we have a `wasmer_named_extern_vec_t`, it's easier; note the `wasmer_named_extern_module`, `wasmer_named_extern_name` and `wasmer_named_extern_unwrap` functions to respectively get the module name, the import name, and the extern/import itself for a `wasmer_named_extern_t`). Finally we insert it in the `wasm_extern_vec_t`.

Why this approach works? Because `wasm_module_imports` returns the import signatures in the correct order that is expected when instantiating the module.

Do you need a concrete example? It's probably a good idea to write an example in our C example collection anyway, because it's really not trivial.

Note: We should also probably provide an unstable API like `wasmer_importobject_t`, because manipulating imports in C is really a nightmare.

**Comment by shingfeel** [comment]
Thanks @Hywan for the answer!

**Comment by lucianoiam** [comment]
I was looking for the same and  `wasi_get_unordered_imports()`  did the trick. +1 on improving the C API in this regards. Here is an alternate version of WASI/host imports mixing that others might find useful since resources are still scarce https://github.com/lucianoiam/hiphap/blob/6d90bd4cbaa41fef15f4522cbc891947a8634d8d/src/WasmHostPlugin.cpp#L106
