### ISSUE TITLE
add static link library build options!

### ISSUE THREAD

**Issue by calvin2021y** [wasmerio/wasmer#2466]
Thanks for proposing a new feature!

### Motivation

add options to build without libffi and genrate static library to link into static execute binary.

**Comment by syrusakbary** [comment]
Hi @calvin2021y, I believe libffi is no longer needed/used in order to compile a static library.

Wasmer also ship with static libraries in each of the releases, so you can reuse them in case it's useful.
If you want to build the c-api locally you can also run this on the root:

```
make build-capi
```

Hope this helps! (please let me know if you need anything else)
