### ISSUE TITLE
wasi_config_delete is missing in the C bindings

### ISSUE THREAD

**Issue by tudor** [wasmerio/wasmer#2468]
One can create a `wasi_config_t` using `wasi_config_new`, but there's no corresponding `wasi_config_delete` to delete it.

If we're able to successfully call `wasi_env_new` with the created config, the env takes ownership and so we shouldn't delete the config ourselves, but it would be good to have a `wasi_config_delete` function to delete the config in the case we realize partway that we can't proceed.

**Comment by Hywan** [comment]
Hello @tudor,

That's a legitimate feature request. [The `wasm_engine_new_with_config` function](https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/engine/fn.wasm_engine_new_with_config.html) takes the ownership of the `wasm_config_t` and that's why we have not implemented a `wasm_config_t`.

And that's the “ah” moment where I realise you're actually talking about `wasi_config_t`, not `wasm_config_t`! And… that's the same explanation. Creating a `wasi_config_t` without calling `wasi_env_new` doesn't make sense… except if you have error handling somewhere, just like you describe.

So yup. Do you want to open a PR for that?
