### ISSUE TITLE
C-API: there is no public interface to wasm_val_vec_t* contents

### ISSUE THREAD

**Issue by lucianoiam** [wasmerio/wasmer#2487]
Unless casting the pointer to a custom struct like this:

```C
struct custom_wasm_val_vec_t {
    int         length;
    wasm_val_t* val;
};
```

But this can break as it is outside developer's control.

**Comment by helmutkian** [comment]
No need for a custom struct. See the standard `wasm.h` for the struct definitions for vector types: 

https://github.com/WebAssembly/wasm-c-api/blob/master/include/wasm.h#L77
https://github.com/WebAssembly/wasm-c-api/blob/master/include/wasm.h#L329

The definition of `wasm_val_vec_t` is:

````c
typedef struct wasm_val_vec_t {
    size_t size; 
    wasm_vec_t * data;
} wasm_val_vec_t;
````

You can access elements of the vector thusly:

````c
wasm_val_vec_t val_vec = WASM_ARRAY_VEC(some_array_of_vals);

val_vec.data[index];
````

This goes for all vector types. Just refer to the header file.

**Comment by lucianoiam** [comment]
I see, thanks for the detailed reply. I overlooked the way vector structs are declared, in this case `WASM_DECLARE_VEC(val, )`.

However does not this break code navigation? in case someone uses a sophisticated code editor. In fact I overlooked the definition by simply running `grep -r` on the Wasmer files for `wasm_val_vec_t`. I usually use this method rather than reading the entire headers of projects files.

Another thing I don't understand, what is a "standard" `wasm.h`?  is it different to the version shipped with the official Wasmer releases? https://github.com/wasmerio/wasmer/releases/tag/2.0.0

Is the C API interface to WebAssembly standardized?

**Comment by helmutkian** [comment]
> Is the C API to WebAssembly standardized?

Yes, there's a common C API defined in order to provide a consistent interface across different runtime implementations: https://github.com/WebAssembly/wasm-c-api

The Wasmer C API README explicitly states compatibility with the common C API:

https://github.com/wasmerio/wasmer/tree/master/lib/c-api#wasmer-c-api---

> This crate exposes a C and a C++ API for the Wasmer runtime. It also fully supports the wasm-c-api common API.

The `wasmer.h` shipped with Wasmer releases is the same as the common header file.

> However does not this break code navigation? 

You can raise that issue on the WebAssembly C API repo. I don't write C directly to interact with the C API. My concern is providing bindings to the Wasmer runtime for another language.

**Comment by lucianoiam** [comment]
Thanks again, this is revealing and very good to know. I don't think the navigation/highlighting issue is a big concern. Will close the thread now, cheers!
