### ISSUE TITLE
Big Array Into Memory

### ISSUE THREAD

**Issue by cyrillicw** [wasmerio/wasmer#2497]
I am writing a simple WASM program that reads a string from a file (as a buffer of bytes), splits it, and prints the splitted parts.

If the size of the buffer is small, then everything works OK. But if I increase the size up to 16KB, then the program works strange: it does not split the row so the splitted array consist of a single string.

Code for WASM:
```
extern "C" {
  fn open_file(ptr: u32, len: u32) -> u32;
  fn read_from_file(ptr2: u32, streamId: u32) -> u32;
  fn print(ptr: u32, len: u32);
}

fn print_str(msg : &str) {
  unsafe {
    let b = msg.as_bytes();
    print(b.as_ptr() as u32, msg.len() as u32);
  }
}

#[no_mangle]
pub extern "C" fn exchange() -> () {
  unsafe {
    let path = String::from("src/test.txt");
    let streamId = open_file(path.as_ptr() as u32, path.len() as u32);
    let body: &mut Vec<u8> = &mut vec![];
    let ptr2 = body.as_mut_ptr();
    let body_len = read_from_file(ptr2 as u32, streamId);
    let slice = unsafe { std::slice::from_raw_parts(ptr2, body_len as usize) };
    let contents = std::str::from_utf8(&slice).unwrap();
    let values = contents.split(";");
    for value in values {
      print_str(value);
    }
  }
}
``` 

Code of buffer filling in VM:

```
fn read_from_file(ctx: &mut Ctx, ptr: u32, stream_id: u32) -> u32 {
    let memory = ctx.memory(0);
    const buffer_size: usize = 16 * 1024;
    let mut buffer: [u8; buffer_size] = [0; buffer_size];
    let manager: &mut ContextManager = unsafe { &mut *(ctx.data as *mut ContextManager) };
    let _ = match manager.read_from_file(stream_id, &mut buffer) {
        Ok(length) => {
            for i in 0..buffer_size {
                memory.view()[ptr as usize + i].set(buffer[i])
            }
            return length as u32;
        }
        Err(e) => { return 0; }
    };
}
```

**Comment by Michael-F-Bryan** [comment]
It looks like your code is incorrect here. Your `read_from_file()` implementation assumes the buffer pointed to by `ptr` has at least `buffer_size` bytes of space, but when you create a new vec (i.e. `let body = &mut vec![]`) the `vec` has zero size and your `read_from_file()` function tries writing `16*1024` bytes into it anyway (a buffer overflow).

The "the program works strange" you are seeing is probably because that buffer overflow clobbered something important.

What you should do is update your `read_from_file()` function to take a `length` parameter saying how much space is in the buffer, then make sure the `body` has an appropriate size.

```rust
#[no_mangle]
pub unsafe extern "C" fn exchange() {
    const BUFFER_SIZE: usize = 16 * 1024;

    let path = "src/test.txt";
    let streamId = open_file(path.as_ptr() as u32, path.len() as u32);

    let mut body = vec![0; BUFFER_SIZE];
    let bytes_written = read_from_file(body.as_mut_ptr() as u32, BUFFER_SIZE as u32, streamId);
    let slice = &body[..bytes_written];
   
    ... 
}
```

**Comment by cyrillicw** [comment]
It works!! Thank you very much
