### ISSUE TITLE
How to import table?

### ISSUE THREAD

**Issue by RazerTang** [wasmerio/wasmer#2582]
My code as below:
> ```
>#include <stdio.h>
>#include <emscripten/bind.h>
>#include <emscripten/emscripten.h>
>
>using namespace emscripten;
>
>class Fib
>{
>public:
>   int Compute(int n)
>    {
>        if (n <= 0)
>            return 0;
>        if (n <= 2)
>           return 1;
>        return Compute(n - 2) + Compute(n - 1);
>    }
>};
>
>EMSCRIPTEN_BINDINGS(fib)
>{
>    class_<Fib>("Fib")
>        .constructor<>()
>        .function("compute", &Fib::Compute);
>}
> ```

> ```
> em++ --bind -o fib2.js fib2.cc
> ```

> ``` 
> wasmer run fib2.wasm
> error: failed to run `fib2.wasm`
>╰─> 1: Emscripten requires at least one imported table
> ```

My question is how to import table here? After imported table, I would like use `--invoke` to call Fib.Compute as below:
> ```
>  wasmer fib2.wasm --invoke new Fib().Compute 13
> ```

Thank you for any answer.

**Comment by jcaesar** [comment]
I'd like to ask you: What do you expect to happen on `wasmer run`? You code defines an algorithm, but nothing that is runnable like an executable. What should run?

Also, I think (but am not sure) that `EMSCRIPTEN_BINDINGS` exists so you can seamlessly use C++ classes from JavaScript as if they were JS classes. But if you're running wasm in wasmer, there isn't any JS that could make use of those bindings. So why do you create them?

<details>
<summary>For completeness, some code that you can feed to `wasmer run`.</summary>

```                                                                                                                                                                            
#include <stdio.h>

class Fib
{
    public:
        Fib() {}
        ~Fib() {}

        int Compute(int n)
        {
            if (n <= 0)
                return 0;
            if (n <= 2)
                return 1;
            return Compute(n - 2) + Compute(n - 1);
        }

};

extern "C" int fib(int n) {
    return Fib().Compute(n);
}

int main() {
    printf("fib(42) = %d", fib(42));
}
```
Compile with
```
em++ -O3 -Wl,--export=fib -o foo.wasm  foo.cpp
```
which gives both a runnable executable with a `_start` entrypoint, and an exported `fib` function to be [called when using wasmer as a library](https://github.com/wasmerio/wasmer/blob/dc7e8b1027b7a297d75b3cfcc792dfe98c42dba5/examples/exports_function.rs#L70-L76).

</details>
(Side note: I had a slight deja-vu because of #2578 doing the same thing in Rust.)

**Comment by RazerTang** [comment]
Thank you for reply.
In your case, If you not have a `main` function, you could call like this:
`wasmer fib.wasm --invoke fib 13`

I just wonder `wasmer --invoke` how to work on  class function. May be called like this
`wasmer fib.wasm --invoke new Fib().Compute 13`

**Comment by jcaesar** [comment]
> I just wonder wasmer --invoke how to work on class function. May be called like this
> ```
> wasmer fib.wasm --invoke new Fib().Compute 13
> ```

Nope, that won't work. I can name you two technical reasons:
* `wasmer run --invoke` can only invoke *symbols* that have been exported, i.e. appear in `wasmer inspect fib.wasm`'s export list
* When using `--invoke`, the wasm binary needs to be fully standalone, i.e. it cannot rely on imports for either wasi or emscripten. (That limitation feels arbitrary, but it is nevertheless in place.)

I think you should investigate a bit how imports and exports work, and how `EMSCRIPTEN_BINDINGS` achieves its functions through them. That might help you understand that this kind of thing can't work, and what you could do instead.

By the way, what is your end goal with this, what do you hope to achieve?

**Comment by RazerTang** [comment]
> > I just wonder wasmer --invoke how to work on class function. May be called like this
> > ```
> > wasmer fib.wasm --invoke new Fib().Compute 13
> > ```
> 
> Nope, that won't work. I can name you two technical reasons:
> 
> * `wasmer run --invoke` can only invoke _symbols_ that have been exported, i.e. appear in `wasmer inspect fib.wasm`'s export list. `new Fib().Compute` is an expression, and would need some kind of interpreter other than a webassembly engine.
> * When using `--invoke`, the wasm binary needs to be fully standalone, i.e. it cannot rely on imports for either wasi or emscripten. (That limitation feels arbitrary, but it is nevertheless in place.)
> 
> I think you should investigate a bit how imports and exports work, and how `EMSCRIPTEN_BINDINGS` achieves its functions through them. That might help you understand that this kind of thing can't work, and what you could do instead.
> 
> By the way, what is your end goal with this, what do you hope to achieve?

I just want to do a test, how to use wasmer to call function of c++ class.

**Comment by RazerTang** [comment]
> I note you can get this confusing "table" error just by giving Emscripten the wrong build target (js instead of wasm)
> 
> ```
> # (echo '#include <stdio.h>' && echo 'int main() { printf("Hello, World!\\n"); return 0;}') > hello.c
> # emcc *.c -o hello.js
> # wasmer hello.wasm
> error: failed to run `hello.wasm`
> ╰─> 1: Emscripten requires at least one imported table
> ```
> 
> i.e. this works
> 
> ```
> # emcc *.c -o hello.wasm
> # wasmer hello.wasm
> Hello, World!
> ```

Thankd you,  the error warning has gone by use new build target.
Now I have the same issue as you. [https://github.com/wasmerio/wasmer/issues/2589](issue)

**Comment by jcaesar** [comment]
> I just want to do a test, how to use wasmer to call function of c++ class.

I promise you, you won't have any fun with that. Consider this: When doing FFI between Rust and C++, for a long time, implementing a C shim was the most reasonable way to get the two to work together. You're trying to do FFI from whatever is hosting the wasm, and C++. Same problem.
And same solution. Define a C interface.

Note that it's of course not *impossible*. Just a very bad idea.
```
em++ -Wl,--export=fib -Wl,--export=_ZN3Fib7ComputeEi --no-entry -o fib.wasm  fib.cpp
wasmer run fib.wasm --invoke _ZN3Fib7ComputeEi 0 20
```
* You'll have to deal with C++ name mangling
* I'm passing `0` here for `this`, since I can get away with it. But it's probably UB.
* You can't invoke `new`, you can only allocate memory and then invoke the constructor on that memory area. (Think placement-new)
* You'll be depending on C++ ABI intricacies everywhere.

* If you want to invoke more than one function (`new Fib().Compute(42)` is 3: allocation, placement new, compute), you'll build your own wasm host application (i.e. use wasmer as a library - this isn't terrible like the 4 other points, but you'll still need to do it).

**Comment by RazerTang** [comment]
Thank you. I got it. C interface should be a good choice instead of C++ inteface.
