### ISSUE TITLE
unhandled trap

### ISSUE THREAD

**Issue by bbday** [wasmerio/wasmer#2604]
I use WasmerSharp c#
when try to call a specific function "push" i have this error: 
**error: "unhandled trap at 7ffbf66a59e5 - code #80000003: breakpoint"**
```
            int bufferMemory = 16777216;
            var stackf = _instance.Call("stackSave")[0];
            var inputBuff = new byte[bufferMemory];
            var nrOfSamples = 32;
            var colStartSampleNr = (int)_instance.Call("stackAlloc", nrOfSamples)[0];
            _instance.Call("pull", colStartSampleNr, nrOfSamples)
```

How i can avoid it? on Chrome this file can run without issue

target file [wasm file](https://1drv.ms/u/s!AulOcG5BxeF6hqEWBbV0rMgcKlKLiw?e=iZeeYE)

**Comment by jcaesar** [comment]
You're probably better off reporting this on https://github.com/migueldeicaza/WasmerSharp.
One thing that confuses me is that it looks like your model.wasm is using emscripten-related imports, but I don't see you setting those up. Maybe that's normal with WasmerSharp. Still, a full reproducing example gist might be a good idea.

(Reattached [module.wasm.gz](https://github.com/wasmerio/wasmer/files/7343041/module.wasm.gz) because onedrive is pain.)

**Comment by jcaesar** [comment]
Probably a good idea to [link](https://github.com/migueldeicaza/WasmerSharp/issues/20#issue-1023730614) that then.
