### ISSUE TITLE
Ctx cannot impl Send

### ISSUE THREAD

**Issue by zutils** [wasmerio/wasmer#287]
In an effort to use an instance in an Arc<Mutex< Instance >>, Ctx does not impl Send.  After reading the docs, "impl !Send for Ctx" is auto-implemented. Does this mean that I cannot use wasmer in multithreaded applications? Is there a temporary workaround until I can?

**Comment by lachlansneff** [comment]
`Instance` should have `Send` implemented on it, forgot to explicitly add it.

**Comment by autodidaddict** [comment]
@lachlansneff this is still a problem in the current version, and it makes it extremely difficult to try and build wrapper libraries and components on top of a wasmer `Instance` struct.

**Comment by lachlansneff** [comment]
@autodidaddict I'm no longer working at Wasmer, I'm not sure who owns that particular piece of code now. The situation may have changed since I last worked on this, but the problem was that `Instance` could not be `Send` because it contained `Rc` references to things, and it was pretty much impossible to change that without a major rewrite.

**Comment by syrusakbary** [comment]
@autodidaddict @zutils we will spend time soon on making `Instance` to implement `Send` and `Sync`

**Comment by syrusakbary** [comment]
More info #748

**Comment by MarkMcCaskey** [comment]
`Instance` now implements `Send`!  I believe this issue should be resolved.  If it's not, feel free to reopen this and we'll investigate it!
