### ISSUE TITLE
Fix rust toolchain issues in Build process, Github Actions

### ISSUE THREAD

**Issue by epilys** [wasmerio/wasmer#3055]
After github actions were recently upgraded to change rust toolchains, some of the builds in [`build.sys`](https://github.com/wasmerio/wasmer/runs/7590802180?check_suite_focus=true) stopped completely working.

**Comment by silwol** [comment]
There are two distinct issues at play here:
* `macos-arm64` build fails because we attempt to reset the `rustup` override with `rustup override set stable` at the end of the **Build Minimal Wasmer Headless** step, but in this case we should do that with `rustup override unset` in order to avoid side effects
* `linux-musl-x64` is built on the `alpine` docker container, and apparently `~` is set by [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain/) but is is not correctly read from the `$PATH` environment variable. This needs to be fixed upstream, replacing `~` with `$PATH` when adding to `GITHUB_PATH`.

**Comment by silwol** [comment]
Closed by https://github.com/wasmerio/wasmer/pull/3060 and https://github.com/dtolnay/rust-toolchain/pull/28
