### ISSUE TITLE
too many runtime missed

### ISSUE THREAD

**Issue by mccoysc** [wasmerio/wasmer#308]
for example:
invoke_iiiiiii
___cxa_end_catch
___cxa_begin_catch
_llvm_eh_typeid_for
_pthread_getspecific
_pthread_key_create
_pthread_once

and so on

you can try to run the attached wasm file and you will find these missed.

**Comment by mccoysc** [comment]
[she_c.zip](https://github.com/wasmerio/wasmer/files/3021615/she_c.zip)

**Comment by MarkMcCaskey** [comment]
Thanks for the report!  I'll get back to you when we've fixed it!

**Comment by MarkMcCaskey** [comment]
Just a heads up, I'm shipping a fix which adds stubs for those functions... Wasmer currently doesn't support exceptions or pthreads but we're very busy adding lots of new features!  Let me know if there are still issues or your use-case relies on those features!

After adding these, it's failing due to a lack of exports.  When running in Emscripten mode, we expect certain functions to be defined.

I'd love to know what you're working on!  And also, if it helps, 因為我可以慢慢的看懂中文所以你可以用中文
