### ISSUE TITLE
C-API Wasi example do not work with 2.3.0

### ISSUE THREAD

**Issue by beef331** [wasmerio/wasmer#3168]
### Describe the bug

I'm presently wrapping the C-API for Nim, and I've found that the some C-API examples are not accurate for 2.3.0. The wasi.c example especially lacks compilable code:

`wasi_env_new` only takes a single parameter in 2.3.0
`wasi_env_initialize_instance` doesnt exist in 2.3.0

### Steps to reproduce

Copy the wasi.c example and compile with `gcc -I$(wasmer config --includedir) wasi.c`.

### Expected behavior

Example works with the present version

**Comment by syrusakbary** [comment]
Thanks for creating the issue. We need to investigate which file are you referring to, because in current `master` we have changed the C-API and it's reflected in the migration guide already: https://github.com/wasmerio/wasmer/blob/master/docs/migration_to_3.0.0.md#c-api

(although we haven't published Wasmer 3.0 just yet)

**Comment by beef331** [comment]
Ah I assumed language integration would link to the most recent release version, so I guess i was falling 3.0.0 with 2.3.0 bindings.
