### ISSUE TITLE
MetadataHeader::CURRENT_VERSION was not bumped between 2.2 and 2.3

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#3193]
Hey all!

We are currently experiencing segfault crashes when using modules that have been serialized to disk with Wasmer 2.2.0 and deserialized with 2.3.0. We are aware the format can change between minor and even patch versions and have a way to handle `MetadataHeader::CURRENT_VERSION` bumps. But it seems that `MetadataHeader::CURRENT_VERSION` was not changed and is still at `1`.

This was discussed in https://github.com/wasmerio/wasmer/issues/2781 but I don't fully understand if and how it has been resolved. Basically from our use case the request is this: the format can change any time, no problem. But we should have a way to detect that (such as reading `MetadataHeader::CURRENT_VERSION` or using a different API). Then we know we have to invalidate the file system cache and everyone is happy. Invalidating the cache for every minor wasmer bump would be a huge computational burden since all the modules have to be recompiled. Would be great if we can avoid that if necessary.

**Comment by syrusakbary** [comment]
This could be solved by three different ways:
1. Support this on rkyv: https://github.com/rkyv/rkyv/issues/115
2. Add example serialized artifacts to the repo that should be working, and test on the CI (so we know when things break)
3. Stick to semver versioning for the artifact crate (and add that version into the serialized information)

IMO if we do 3, then we need to also do 2 as safeguard.
If we do 1, 2 might also be needed, but 1 by itself is already a bit more safe (since it's depending on a precomputed hash that does things for us)

**Comment by webmaster128** [comment]
I'm fine with something like 1. This keeps it simple and relyable and just tells us _nothing changed_ vs. _something changed that might potentially affect you, better recompile_.

I think I don't understand "semver versioning for the artifact crate". Which crate are you referring to?
