### ISSUE TITLE
Error while importing "__wbindgen_placeholder__"."__wbg_new_abda76e883ba8a5f"

### ISSUE THREAD

**Issue by knarkzel** [wasmerio/wasmer#3243]
### Describe the bug

When trying to run a web assembly file that uses following crates: ![solana_sdk](https://docs.rs/solana-sdk/latest/solana_sdk/) and ![tiny-bip39](https://docs.rs/tiny-bip39/latest/bip39/) with following source code:

```rust
use solana_sdk::signature::keypair_from_seed;
use bip39::{Language, Mnemonic, MnemonicType, Seed};

#[no_mangle]
pub extern fn main() -> Option<Box<String>> {
    let mnemonic = Mnemonic::new(MnemonicType::Words12, Language::English);
    let passphrase = "qwerty123";
    let seed = Seed::new(&mnemonic, &passphrase);
    keypair_from_seed(seed.as_bytes()).map(|it| Box::new(it.to_base58_string())).ok()
}
```

Compiled with `cargo build --release --target=wasm32-wasi` I get following errors:

```shell
space-operator/wasm/rust via (shell) ❯ wasmer run keypair.wasm
error: failed to run `keypair.wasm`
╰─▶ 1: Error while importing "__wbindgen_placeholder__"."__wbg_new_abda76e883ba8a5f": unknown import. Expected Function(FunctionType { params: [], results: [I32] })
```

```sh
wasmer 2.1.1 | rustc 1.65.0-nightly (878aef79d 2022-08-20) | x86_64
```

### Expected behavior

It should work.

### Actual behavior

It crashes with "unknown import".

**Comment by knarkzel** [comment]
Also happens on wasmer-3.0.0beta2.

**Comment by Michael-F-Bryan** [comment]
This happens when one of your dependencies pulls in [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen) when compiling to the `wasm32` architecture. `wasm-bindgen` uses some code which only works when running in a browser environment and their glue code (the `*.js` files it generates).

I'd suggest looking through your dependency tree to see which crate pulls in `wasm-bindgen` and find out how to disable it. The `cargo tree` command can be useful here.

**Comment by Michael-F-Bryan** [comment]
I'll close this ticket for now because it's not an issue with wasmer.
