### ISSUE TITLE
`wasmer binfmt register` calls `copy_file_range` with invalid file descriptor

### ISSUE THREAD

**Issue by vi** [wasmerio/wasmer#3376]
### Describe the bug

```
# /opt/wasmer/bin/wasmer --version
wasmer 3.0.1

# strace /opt/wasmer/bin/wasmer binfmt register
...
openat(AT_FDCWD, "/opt/wasmer/bin/wasmer", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/tmp/.tmpuky8ss/wasmer-binfmt-interpreter", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0100755) = 4
copy_file_range(-1, NULL, -1, NULL, 1, 0) = -1 EBADF (Bad file descriptor)
copy_file_range(3, NULL, 4, NULL, 1073741824, 0) = 74246920
copy_file_range(3, NULL, 4, NULL, 1073741824, 0) = 0
close(4)                                = 0
close(3)                                = 0
...
```

### Expected behavior

No obviously wrong syscalls issued.

---

(actually started creating a report that it deletes temporary files used for registering binfmt_misc, leaving `interpreter` dangling in `/proc/sys/fs/binfmt_misc/wasm32`, but then discovered that it works anyway, so only minor secondary problem remained in the bug report).

**Comment by Michael-F-Bryan** [comment]
Thanks for reporting this @vi! 

If `wasmer binfmt register` seems to be working, it might be that a `std::io::Error` is raised internally and `wasmer` automatically handles it.

I'm going to close this because everything seems to be working as expected, but feel free to reopen the ticket if you feel this isn't the case.
