### ISSUE TITLE
Using `FunctionEnvMut` in an async context

### ISSUE THREAD

**Issue by sagacity** [wasmerio/wasmer#3382]
### Summary

I have a `TypedFunction` that spawns a Tokio task and returns a handle to that task as a future to the guest (WASM) code. The WASM code awaits this future. Once the Tokio task is completed it will resolve the future.

In Wasmer 3 I implement this `TypedFunction` like so:
```
pub fn make_http_request(env: FunctionEnvMut<Env>, request: ...some data...) -> PromisePtr {
    let promise_ptr = create_promise(&mut env);
    let handle = tokio::runtime::Handle::current();
    handle.spawn(async move {
        let result = do_some_async_work().await;
        // do some work with `env` to grab the WASM export to call to resolve the promise on the WASM side
    });
    promise_ptr
}
```

However, `FunctionEnvMut` is not `Send`, since the store it embeds contains (among other things) a `wasmer_vm::Instance::InstanceHandle`, which is not `Send`. This makes it impossible to use `env` in my async closure.

Am I not supposed to be able to move `FunctionEnvMut` to another thread? Is there another way to achieve the same result?

**Comment by theduke** [comment]
`FunctionEnvMut` requires mutable access to the underlying store, so it can't be shared and it's lifetime must be restricted to the duration of the callback.

`FunctionEnv` is shareable though.
You can upgrade it to a mutable one with [FunctionEnv::as_mut](https://docs.rs/wasmer/latest/wasmer/struct.FunctionEnv.html#method.as_mut).

**Comment by sagacity** [comment]
@theduke thanks for the reply. As far as I understand it, the callback passed to `new_typed_with_env` can accept either a `FunctionEnv` or a `FunctionEnvMut`. Indeed, I originally used `FunctionEnv`, but I can only upgrade it to `FunctionEnvMut` if I have access to the `Store`, which is not passed in as an argument to the callback.

How should I create a `TypedFunction` through `Function::new_typed_with_env` that has access to the store, so that I can upgrade the `FunctionEnv` argument to a `FunctionEnvMut` later inside the function?

**Comment by theduke** [comment]
Ah, right, I overlooked that you are trying to get mutable access to the store inside the async function.

That's not possible, because at that point the instance has resumed it's own execution in it's own thread, so getting mutable access to the environment is not possible.

What you can  do is store the result of the async computation in some shared type (like an `Arc<Mutex>`, or use a channel like `tokio::sync::oneshot` to send the result.

Then you have to implement some kind of polling host function that the client can call to retrieve the output with a handle id, either by checking if it is available and returning an empty value otherwise, or by blocking until it becomes available (use a channel for that!)

This is general Rust advice though.

From the Wasmer perspective the simple answer is: you can only get mutable access to the environment inside provided host functions.

**Comment by theduke** [comment]
ps: the simplest thing to do is to just use something like tokio [RuntimeHandle::block_on](https://docs.rs/tokio/latest/tokio/runtime/struct.Handle.html#method.block_on) and only return from the host function once the value is available.

**Comment by theduke** [comment]
I'm pretty new to Wasmer, so I can't give you a definitiv answer,  but I'm pretty sure that previous code would have been unsound, because you couldn't have had any guarantees about the  (memory) state of the instance.
