### ISSUE TITLE
runtime-c-api should not copy files to manifest directory

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#354]
`cargo publish` is unhappy with modifications happening outside of `OUT_DIR` when running build.rs.

**Comment by bjfish** [comment]
I'm guessing the current build must changing the last modified time of the file and complaining about that since the contents shouldn't change.

I wonder if we could configure the header generator not to modify the file if the contents have not changed.

Link to rust feature:
https://github.com/rust-lang/cargo/pull/5584

**Comment by Hywan** [comment]
@MarkMcCaskey I believe we can close this issue now. Feel free to reopen if you think it's still relevant somehow.
