### ISSUE TITLE
How to deal with "Function prologues cannot exceed 255 bytes in size for Windows x64"

### ISSUE THREAD

**Issue by sagacity** [wasmerio/wasmer#3559]
A user of our binding generator [reported](https://github.com/fiberplane/fp-bindgen/issues/171) that they are getting an error during compilation of WASM code on their Windows machine: "Function prologues cannot exceed 255 bytes in size for Windows x64".

This error seems to come from `unwind_winx64.rs` which deals with generating Windows x64 unwind info.

My main question would be, what can we do about this issue? The error doesn't give any indication on what to do. I've looked at perhaps disabling generating the unwind info by disabling the `unwind` feature but this does not seem to be exposed directly by `wasmer` (it comes from the various compiler crates). Is there perhaps something we can do on our end to make the unwind info smaller, so it doesn't exceed this limit?

**Comment by ptitSeb** [comment]
@sagacity , with the update of Wasmer to v3.2.1, is this issue still there?

**Comment by sagacity** [comment]
Unfortunately I am not working on this project anymore, but perhaps @kajacx has some time to take a look.

**Comment by kajacx** [comment]
@ptitSeb hello, I am currently ill, it will be a few weeks before I can take a look at it. From what I remember, just running the wasmer example on my windows 10 machine created the problem.

**Comment by ptitSeb** [comment]
Oof, a few weeks, sorry.

I tried some examples with latest wasmer and didn't had any issue on my Windows 10 machine. I'll wait for your return and some info about how to reproduce it.

**Comment by kajacx** [comment]
@ptitSeb I just tried it and with the wasmer3 upgrade (on the current [`wasmer3`](https://github.com/fiberplane/fp-bindgen/tree/wasmer3) branch ([commit](https://github.com/fiberplane/fp-bindgen/tree/f0613368c77ab178c1e8cc7c122ec12c478bc778))), the issue is no longer present.

**How to reproduce:**

To reproduce the original issue with wasmer2, you can clone the [`main`](https://github.com/fiberplane/fp-bindgen/tree/main) branch ([commit](https://github.com/fiberplane/fp-bindgen/tree/4e95816ded538ff7bde4ddf1d460326d95dff046)) and run this script in the `examples` folder:

```sh
echo "Generating protocol..." && \
cd example-protocol && cargo run && cargo test && cd .. && \
echo "Protocol generated, building plugin..." && \
cd example-plugin && cargo build && cd .. && \
echo "Plugin built, running wasmer runtime test..." && \
cd example-rust-wasmer2-runtime && cargo test && cargo test --features wasi && cd .. && \
echo "Wasmer test success, running deno runtime test..." && \
cd example-deno-runtime && deno test --allow-read tests.ts && cd .. && \
echo "All done."
```

**Verify that it's fixed:**

Similar script can be ran on the wasmer3 branch to verify that the issue is fixed, but:

1. Remove `cargo test` on second line, snapshots are not updated.
2. Rename `example-rust-wasmer2-runtime` to `example-rust-wasmer-runtime` on 6th line.
3. Remove `cargo test --features wasi` on sixth line.

Then running the script works, but it blows mine CPU to 100%, even on subsequent runs, and says that some tests took over 60 seconds. This is probably unrelated problem.

**Conclusion:**

It's fixed by using wasmer3, so going back to wasmer2 and fixing the problem there probably isn't worth while.

**Comment by ptitSeb** [comment]
Looks good to me, the ticket can be closed then?
