### ISSUE TITLE
Support for golang: golang-ext-wasm

### ISSUE THREAD

**Issue by 0zAND1z** [wasmerio/wasmer#378]
Is it currently possible for a golang program to execute a WASM Binary through `wasmer` specifically?

If this is currently not supported, I hope it makes sense to have a separate golang package to handle this. 

Happy to contribute to a potential `golang-ext-wasm` :)

**Comment by bjfish** [comment]
Hi @0zAND1z , golang doesn't execute yet but I currently have a work in progress branch: https://github.com/wasmerio/wasmer/tree/feature/golang

I am trying to run a "Hello, Webassembly" go lang application here:
https://www.dropbox.com/s/xdqtfncuze2qrff/main.wasm?dl=0
which was compiled with a go 1.12.

I run this file with: `cargo +nightly run --features "backend:singlepass debug" run ../scripts/main.wasm` since the singlepass feature can compile the 2.6mb binary faster. This command currently fails with:
`thread 'main' panicked at 'syscallJsValueGet not yet implemented', lib/golang/src/lib.rs:125:5`

If you would like to contribute on this, I have all the imports defined here but more need to be implemented: https://github.com/wasmerio/wasmer/blob/feature/golang/lib/golang/src/lib.rs
Golang defines the imports in javascript here: https://github.com/golang/go/blob/master/misc/wasm/wasm_exec.js. Thanks.

**Comment by losfair** [comment]
@bjfish I think @0zAND1z means a Golang binding to wasmer, like a Go version of `python-ext-wasm`?

**Comment by bjfish** [comment]
@losfair Thanks for clarification, I will move my comment to the other issue.

**Comment by Hywan** [comment]
I can work on it yes. Not sure it's a priority right now though. Let me try!

**Comment by 0zAND1z** [comment]
@Hywan , I read your [blog post](https://medium.com/wasmer/announcing-the-fastest-webassembly-runtime-for-go-wasmer-19832d77c050) & that is quite spot on!

Me and my team from India would love to contribute & I would like to ping you later in the community.
Link to the proposed golang-ext-wasm: https://github.com/wasmerio/go-ext-wasm 

I am sure the blockchain community would make the best out of it.
Closing this issue for now. Thanks again for such a quick response!
