### ISSUE TITLE
`fflush` doesn't work on WASI

### ISSUE THREAD

**Issue by ktock** [wasmerio/wasmer#3790]
### Describe the bug

`fflush` provided by wasi-sdk doesn't work on wasmer.

```sh
wasmer -vV; rustc -vV
wasmer 3.2.0 (8a343d0 2023-04-18)
binary: wasmer-cli
commit-hash: 8a343d0f9a1d3d4b4bfe622ed345253d780a3d76
commit-date: 2023-04-18
host: x86_64-unknown-linux-gnu
compiler: singlepass,cranelift,llvm
sh: 1: rustc: not found
```

### Steps to reproduce

sample C program:

```c
#include <stdio.h>
#include <unistd.h>

int main(int argc, char **argv)
{
  char buf[5];
  int len = 5, ret;

  printf("input something\n");
  printf("> ");
  fflush(stdout);
  ret = read(0, buf, len);
  if (ret > 0) {
    printf("got %.*s (first 5 chars)\n", ret, buf);
  }
  return 0;
}
```

I built this using wasi-sdk 19.0. (`${WASI_SDK_PATH}/bin/clang --sysroot=${WASI_SDK_PATH}/share/wasi-sysroot -o out.wasm main.c`)

On host, prompt (`>`) is printed by `fflush`.

```console
$ gcc main.c ; ./a.out
input something
> hi
got hi
 (first 5 chars)
```

On wasmer, prompt (`>`) isn't printed (isn't flushed).

```console
$ wasmer /app/out.wasm
input something
```

### Expected behavior

fflush works and buffered strings are printed.

### Actual behavior

fflush doesn't work and buffered strings aren't printed.

**Comment by mucinoab** [comment]
I am working on this.

I was able to reproduce the issue in Rust with 

```rust
// Compile with "cargo build --target wasm32-wasi --release"
use std::io::{self, Write};

fn main() {
    let mut buffer = String::new();
    let mut stdout = io::stdout().lock();
    let stdin = io::stdin();

    stdout.write(b"Input something\n").unwrap();
    stdout.write(b"> ").unwrap();
    stdout.flush().unwrap();

    stdin.read_line(&mut buffer).unwrap();
}
```

**Comment by ibrahim-akrab** [comment]
I am trying to look into this but the codebase is quite large I keep jumping from one file to another. Any directions about where the execution of the wasm file happens or where it is passed to the runtime would be much appreciated.

**Comment by mucinoab** [comment]
This issue is basically the same as #363 but it seem that if I run the above reproduction it does not hit the [code path](https://github.com/wasmerio/wasmer/blob/bd75b2b615ac9dc8eb8081e2015fd675178ac8ce/lib/wasi/src/syscalls/mod.rs#L158) that fixed that issue. 

Also, it seems that my explicit flush in the example is not triggering any flush, nor sync syscalls. The only time that we flush is when closing the files [in here](https://github.com/wasmerio/wasmer/blob/bd75b2b615ac9dc8eb8081e2015fd675178ac8ce/lib/wasi/src/fs/mod.rs#L389).

**Comment by mucinoab** [comment]
@ibrahim-akrab Turn on the tracing logs to get some idea.

`wasmer -d program.wasm`

**Comment by syrusakbary** [comment]
The Wasm file is likely properly generated. So it's likely is an issue in the system call layer

**Comment by ibrahim-akrab** [comment]
> Also, it seems that my explicit flush in the example is not triggering any flush, nor sync syscalls. The only time that we flush is when closing the files [in here](https://github.com/wasmerio/wasmer/blob/bd75b2b615ac9dc8eb8081e2015fd675178ac8ce/lib/wasi/src/fs/mod.rs#L389).

The problem kind of lies here. Wasmer waits for sync syscall to flush the output but the sync syscall doesn't get generated even when using native binary. And we shouldn't see any flush call either since all file operations are translated to syscalls and the flush is simply a way to tell libc to execute the `write` syscall now with the data present in the buffer. Wasmer should behave similarly by flushing on every `fd_write` syscall.

When tracing the program execution with `strace` we see the same file syscalls across the native binary and the wasmer executed wasm executed in the same order. The only difference is that when wasmer executes the `fd_write` syscall, it doesn't print the output due to the previously mentioned missing flush.

 I fixed the issue by adding 
```rust
handle.flush().await.map_err(map_io_error)?;
```
before the `Ok` in the match arm:
https://github.com/wasmerio/wasmer/blob/bd75b2b615ac9dc8eb8081e2015fd675178ac8ce/lib/wasi/src/syscalls/wasi/fd_write.rs#L110-L148 

In fact, this also fixes #3814 since it is the same problem.

However, I won't be opening  a PR for it since @mucinoab did most of the work so it's only fair that he gets the bounty.

**Comment by theduke** [comment]
Note that we do not want to just flush on every write, that would penalize performance for the common case.

**Comment by mucinoab** [comment]
> Writing then flushing is an abstraction layer provided by programming languages in order to have control over when the actual syscall is called.

For example, see this item in Rust:
https://doc.rust-lang.org/std/io/struct.BufWriter.html#

Or how the Python print has a _flush_ argument.
https://docs.python.org/3/library/functions.html?highlight=flush#print

But I think the main problem to solve here is why the fflush / flush is not triggering anything. right?

**Comment by ibrahim-akrab** [comment]
It is triggering the write syscall at the specific point in program execution. And that's it's sole job, to make sure anything left in the buffer gets passed to a wrote syscall. So it's working as intended.

What's not working as intended is wasmers fd_write since at the end of a syscall, we should be sure buffer data is all written from memory to the specific file handler. Of course that's not what happens.

The current implementation leaves it to the compiler to decide when to write the data to the file, instead of choosing manually when to write to make it compatible with native binary's execution

**Comment by mucinoab** [comment]
@ibrahim-akrab please take over, I am too busy right now to deal with the urgency. 

Thanks.
