### ISSUE TITLE
Can you attach version to release artifact names?

### ISSUE THREAD

**Issue by KSXGitHub** [wasmerio/wasmer#389]
### Motivation

I maintain an AUR package for wasmer call `wasmer-bin`. And I use `yay` to install `wasmer`. `yay` uses archive names to detect whether the sources need to be downloaded. But wasmer release artifacts all share the same name.

### Proposed solution

Attach version to artifact name: `wasmer-linux-amd64.tar.gz` should become `wasmer-linux-amd64-0.4.0.tar.gz`

**Comment by Hywan** [comment]
Hello,

The version name of the release artifacts is part of the URL, like in https://github.com/wasmerio/wasmer/releases/download/2.0.0/wasmer-linux-amd64.tar.gz. However, since https://github.com/wasmerio/wasmer/pull/2449 and https://github.com/wasmerio/wasmer/pull/2457, the library contains an appropriate `soname` and `current_version` (on macOS), maybe it can help. Otherwise you can also run `wasmer --version`.

I'm closing this issue, but feel free to reopen if I didn't answer your question, or if you need more assistance! I'll be happy to help :-).
