### ISSUE TITLE
Where is wasm.h?

### ISSUE THREAD

**Issue by blitz-research** [wasmerio/wasmer#4087]
Hi,

I am using the c-api lib and the only wasm.h header file I can find for this is in a 'tests' directory (ie: lib\c-api\tests\wasm-c-api\include) which seems odd.

I am building c-api lib using 'make build-capi' which creates the lib in a 'target/release' directory, but again there's no generated output wasm.h header anywhere AFAICT.

That said, the wasm.h in the tests dir seems to work fine, just seems a bit weird...

Bye,
Mark

**Comment by syrusakbary** [comment]
`wasm.h` comes directly from the wasm-c-api which happens to be integrated into this repo via the tests.
https://github.com/wasmerio/wasmer/blob/master/lib/c-api/tests/wasm-c-api/include/wasm.h

Basically, we want to reuse this file and not duplicate it, that's why is coming from tests atm. Fully agree that is not intuitive for it to be in tests, but so far is the best option that we have for now I think. If you have better ideas please let us know!

**Comment by syrusakbary** [comment]
Feel free to respond if you have other questions or suggestions, closing the issue for now :)

**Comment by blitz-research** [comment]
Thanks clearing that up, it's just a bit confusing as there are 3 wasm.h files in the repos - there's a 'link' in c-api, there's what appears to be an old version in c-api/tests, and there's the 'use me' version in c-api/test/wasm-c-api/include.

At the very least, perhaps remove the unused ones?
