### ISSUE TITLE
Ability to set environment variables

### ISSUE THREAD

**Issue by tiborvass** [wasmerio/wasmer#475]
I couldn't find a way to set an environment variable neither in the help nor in the Rust code.

### Motivation

Because it's an easy way to configure a program's behavior.

### Proposed solution

Add a `--env key=value` cli option.

**Comment by MarkMcCaskey** [comment]
This would be a nice option to have! 

It looks like wasmer currently forwards along all the host's environment variables by default.  We'll probably make a breaking change here eventually (so the sooner the better, I guess).

We did have a bug with WASI env var syscalls that should be fixed in #476 !  So hopefully they work now
