### ISSUE TITLE
Question: Why the type of pointer in wasm is  WASM_I32

### ISSUE THREAD

**Issue by mrpre** [wasmerio/wasmer#524]
Source:
```
void* hello_wasm(void *ptr)
{
    return ptr;
}
```
```
emcc target.c -Os -s SIDE_MODULE=1 -s EXPORTED_FUNCTIONS="['_hello_wasm']" -o target.wasm
```

I use c-api to detect the param_type and return_type but find all of them are type of  `WASM_I32`. Why not `WASM_I64` ?

The c-api I used
```
wasmer_export_func_returns
wasmer_export_func_params
```

**Comment by piranna** [comment]
Due to current spec, WebAssembly is a 32 bits architecture, with a maximum of 4GB directionable addresses, although it support some 64 bits arithmetic operations. There's a future proposal for 64 bits addressses, but it's not defined. The way to differenciate them will be calling them `wasm32` and `wasm64` architectures, although currently the only one available is the former one.
