### ISSUE TITLE
Getting I/O error when running quickjs (works on wasmtime)

### ISSUE THREAD

**Issue by saghul** [wasmerio/wasmer#569]
### Describe the bug

Running the QuickJS example fails with i/o error:

```
 wasmer run --dir=examples/ build/qjs.wasm -- examples/hello_world.js
examples/hello_world.js: I/O error
```

Source: https://github.com/saghul/wasi-lab/tree/master/qjs-wasi

```bash
wasmer 0.5.6 | rustc 1.35.0 (3c235d560 2019-05-20) | x86_64
```

### Steps to reproduce

1. Clone https://github.com/saghul/wasi-lab/
2. Go into qjs-wasi
3. Build with ./buils.sh
4. Run with the command above
5. See the error

### Expected behavior

The following is printed:

```
Hello World
fib(10)= 55
```

### Actual behavior

I/O error

### Additional context

N/A

**Comment by saghul** [comment]
[qjs.wasm.zip](https://github.com/wasmerio/wasmer/files/3410035/qjs.wasm.zip)

Here is the wasm file, in case that helps debug faster.

Ping @syrusakbary  :-)

**Comment by MarkMcCaskey** [comment]
Hi!  Thanks for reporting this!

I actually have a PR open that's rewriting and improving a ton of our WASI FS code, #555 , and I just tested it and your example works there!

The PR is getting into good shape, I'm just trying to write a lot of tests to cover as many branches of the internal logic as I can to make sure I don't break anything that's already working and to make sure we don't break them going forward.

When we ship it, we'll release a new version of Wasmer because it's a huge improvement.  Optimistically that might be today, but it may be early next week.

**Comment by saghul** [comment]
This is fantastic news, thank you! 🚀

**Comment by syrusakbary** [comment]
This issue is now fixed on wasmer [0.5.7](https://github.com/wasmerio/wasmer/releases/tag/0.5.7).

You can update wasmer locally with:

```
wasmer self-update
```

Let us know if everything is ready for publishing into wapm 🎉

**Comment by saghul** [comment]
This is one is fixed, that was fast! ❤️

**Comment by Munawwar** [comment]
So quickjs seems to compile but can't seem to load it -> https://github.com/saghul/wasi-lab/issues/2
(tried python and ruby wasm ext libraries)
