### ISSUE TITLE
Is it possible to call <windows.h> functions such as MessageBox through WASI?

### ISSUE THREAD

**Issue by brandonros** [wasmerio/wasmer#730]
### Summary

Is it possible to compile WASM code (either directly in the resulting executable or through bindings) that can call Windows library functions? If not, why not and will this ever happen/what is needed to make this happen?

**Comment by brandonros** [comment]
>  Wasm module with access to Windows APIs (generically or otherwise)

With the current state of the wasmer runtime, how would one write a Wasm module that has access to Windows APIs?

**Comment by brandonros** [comment]
I understand the state of things now. 

I would need to write a Wasmer plugin that calls `MessageBox` as an external C function in Rust, compile it to WASM, then I would need to write a wrapper that loads and runs the compiled plugin in its WASM module form (also in Rust).

**Comment by brandonros** [comment]
The answer to my question lies in the output of `wapm run wasm2wat examples/plugin-for-example.wasm` from https://github.com/wasmerio/wasmer/tree/master/examples/plugin-for-example#inspecting-the-plugin

It isn't clear to me how WebAssembly is able to compile a module that makes an external call.

**Comment by MarkMcCaskey** [comment]
So given the way Wasm works, there has to be a translation layer between Wasm and the native functions.  This code _can_ be generated though.  I think this isn't the direction the Wasm community is interested in going.  Though this may be a feature we add far into the future, but at least right now I'm not convinced that allowing Wasm to call into arbitrary native code directly makes sense.

Doing so breaks security and portability, so there's not much reason to even have Wasm code calling into the native code, it seems like just using a native executable is more straightforward.

If you mean doing something like compile-time binding generation based on a header file, similar to what the bindgen libraries in Rust do, then that's a pretty neat idea for a tool to create custom Wasm runtimes.

Perhaps I've misunderstood though, let me know if that doesn't answer your question.

**Comment by brandonros** [comment]
```javascript
const ffi = require('ffi')
const libm = ffi.Library('./libm.dll', {
  'ceil': [ 'double', [ 'double' ] ]
})
libm.ceil(1.5) // 2
```

> So given the way Wasm works, there has to be a translation layer between Wasm and the native functions. 

Unless the WASI described `dl_open` + `dl_sym` + `dl_invoke`, capabilities, right?

> This code can be generated though. I think this isn't the direction the Wasm community is interested in going.

I agree. Compiling <windows.h> and its subheaders down into WebAssembly sounds like a nightmare.

> Though this may be a feature we add far into the future, but at least right now I'm not convinced that allowing Wasm to call into arbitrary native code directly makes sense.

I personally see WebAssembly as something that started in the browser but is growing into something bigger. I see a lot of power behind `wapm run @thatorg/that-thing` where that-thing is a WebAssembly module that can call native modules. It opens a lot of doors.

I don't dispute that it should be behind some explicit "--give-away-all-security-checks" flag, but I'd be curious to hear if/why you think it isn't worth implementing from the perspective of "it makes WebAssembly a more powerful target". Right now, it is limited in what it can interact with (without writing IPC wrappers around DLL methods...)

**Comment by theduke** [comment]
I think this discussion brings up a very interesting point.

Non-trivial applications like GUIs with good host integration  would need access to a huge API surface.

I see a few ways how this could end up working, using the example of a GUI app:

* WASI gains enough platform-independent APIs to enable this, including a solid graphics library abstraction like `wgpu` ( tall order because of the huge API surface which is hard to abstract over)

*  there could be a custom GUI runtime that provides all the required bindings to application code.
Eg: `qtwasm run my-gui-app`, but this would require both the runtime and the application code to be in sync (much harder than eg with `wasmer` and wasm code...) and still would probably have a lot of problem areas due to imperfect. Also this would somewhat "destroy" the platform-independent nature of wasm.

* As described by @brandonros ,   code gets a way to dynamically discover and use host-specific APIs and use them as required; provided via WASI or via Webassembly directly, utilizing things like the new interface types proposal, etc

It'll be interesting to see where things go.

**Comment by brandonros** [comment]
Does the WASM community want "WASM everywhere", though?

**Comment by MarkMcCaskey** [comment]
@theduke I see 1 as the most likely or at least the one I expect the majority to be working on over the coming years and 3 as a fallback if everything else doesn't work.  The problem is that 3 causes a ton of problems that are basically unsolvable, like being unportable, insecure, and allowing Wasm modules to do things like leak kernel resources (which is currently probably possible in ABIs like emscripten but that's theoretically fixable).

I think the solution is that Wasm apps won't, in general, use native host APIs.  Portable graphical Wasm apps will be closer to electron.  The reason is that I don't think portability using host APIs is hard because of a global lack of engineering resources (though that also is a problem), I think it's just a fundamentally hard problem of abstracting over different APIs and something that can't be solved very well.

Additionally, all 3 is really doing is pushing the complexity into the Wasm module which means that old Wasm modules will just stop working as the computing ecosystem changes, which makes using Wasm even more questionable.  If you don't want portability, security, or long-term compatibility, I'm not sure why you'd want to use something like Wasm.  Maybe I'm still misunderstanding what you're saying though.
