### ISSUE TITLE
Ability to load several modules

### ISSUE THREAD

**Issue by mikevoronov** [wasmerio/wasmer#757]
### Summary

Hi, guys! Is it possible to simultaneously load several Wasm modules with Wasmer in such a way that corresponding imports from one module would be linked with corresponding exports from other module?

**Comment by syrusakbary** [comment]
This should be completely doable with the work that we have done in the refactor.

Will close this issue once it lands :)

**Comment by Hywan** [comment]
This issue is resolved to me. A module can import individual externals from an other module (see [the `ImportObject` API](https://docs.rs/wasmer/2.0.0/wasmer/struct.ImportObject.html)). [The Module Linking proposal](https://github.com/WebAssembly/module-linking) is still [at phase 1](https://github.com/WebAssembly/proposals#phase-1---feature-proposal-cg), and it would allow to push things further.

I'm closing this issue :-).
