### ISSUE TITLE
Provide more low-level access to Wasm memory

### ISSUE THREAD

**Issue by michaelvoronov** [wasmerio/wasmer#862]
### Motivation

Currently, Wasm memory could be read and written only byte-per-byte with `view` method. It isn't convenient in all cases. E.g. when it needs to compute hash of memory or log message from memory - these immutable operations need additional copying from Wasm memory to "Rust" memory.

### Proposed solution

I think, it would be really nice if Wasmer will export some more low-level API for dealing with Wasm memory. E.g. either `vm_local_memory` could be public or `ValueType` could be implemented for Wasm Page (it is a more complicated solution in usage, but more satisfying to the current implementation).

**Comment by MarkMcCaskey** [comment]
Thanks for the issue!

Yeah, we have a wrapper that works with `ValueType`s called `WasmPtr` in `wasmer_runtime_core::memory::ptr` that lets you access more interesting types directly in that memory.

We'll have to think about this some more to design a good API, but I agree that this seems important.

Can you explain why getting a slice via `MemoryView` won't work for your use case?

With a slice of bytes, you can check the length and then transmute it into any type you want.  Though, having `transmute` exposed to the user is probably not a good API design just due to how easy it is to mess up and how bad those mistakes can be for security and stability.

**Comment by michaelvoronov** [comment]
Thank you, will look to the `WasmPtr`.

Sorry, I wasn't correct with only byte-per-byte, but I am trying to use transmute as a last resort :). And in this case, there is some excess work for creating MemoryView, so it is better to deal with a raw pointer. Moreover, the approach with transmuting potentially might make more errors than dealing with a raw pointer.

**Comment by michaelvoronov** [comment]
Btw, what do you think about adding `checked_add` in operations like [here](https://github.com/wasmerio/wasmer/blob/977f3a6406e950a005605a0fd089824f383e1d42/lib/runtime-core/src/memory/ptr.rs#L123) in WasmPtr? It there is a check for the right limit, there might be a check for overflow.

**Comment by MarkMcCaskey** [comment]
@michaelvoronov `checked_add` isn't required here because we're adding 2 types cast from 32 bits which means that the maximum value we can get will fit into 33bits.  The fact that it uses `usize` instead of `u64` is an issue on 32bit platforms, but Wasmer has many places where it uses the assumption that it's running on a machine that has a `usize` of at least 64 bits.

it's possible to rewrite this with `checked_add` but I don't immediately see the benefit in doing so. Perhaps it is more explicit and that's good, but it would also be more verbose I think.

Let me know if I misunderstood your reasoning!

In regards to transmute:

I agree, I think an API that relies on the user using transmute correctly is a bad API.  We can probably expose a raw pointer, but that's also pretty error prone.  Hmm, the issue with `WasmPtr<Page>` is that it doesn't guarantee that the starting address is at the start of a page 🤔 .

Another thing to consider in the abstraction that we expose is that: dereffing an unaligned pointer in Rust is undefined behavior.  `WasmPtr` does alignment checks and exposes a safe API, so I like it.

**Comment by michaelvoronov** [comment]
>The fact that it uses usize instead of u64 is an issue on 32bit platforms, but Wasmer has many places where it uses the assumption that it's running on a machine that has a usize of at least 64 bits.

> Let me know if I misunderstood your reasoning!

Didn't know, yes, in this case, `checked_add` just slow down execution a little bit, and it useless until Wasm64 :). This assumption with supporting only 64bit could potentially make problems with embedding (especially on Windows where many programs prefer 32-bit mode - as far as I know, Chrome started to use 64-bit renderer processes for tabs only in 2017), but could be avoided with dynamic processor mode switching.

> Hmm, the issue with WasmPtr<Page> is that it doesn't guarantee that the starting address is at the start of a page 🤔 .

(quick idea) There could be three ctors: one could receive Wasm page number, and another raw offset that will be automatically aligned to Wasm page start and the Wasm page that contains such address will be returned, the third could receive both address and size and returns a slice of Wasm pages contains such range. Also, each Wasm page should expose API to adjust an address from the global memory context and back.

> Another thing to consider in the abstraction that we expose is that: dereffing an unaligned pointer in Rust is undefined behavior.

Agree 👍. Just for example, In Fluence, the most "advanced" memory usage will be for merkalization: we need to track memory chunks that were changed during execution. I am planning to do that by setting the memory protection and signal handler method (a chunk should be a multiple of the OS memory page size). And I think that for this usage `WasmPtr<Page>` is enough.

**Comment by MarkMcCaskey** [comment]
Sorry about the very long delay!  I'm actively working on this now.

After talking about this with @nlewycky , I think we want to provide an API which abstracts away memory.  With this API, users with more advanced use-cases can implement memory to behave exactly as they want.  There are some issues with this design that I think we haven't fully thought through yet and I expect that properly designing and implementing it will take some time.

My, admittedly limited, understanding is that you won't be able to set memory protection and signal handlers today if I were to add `WasmPtr<Page>`; the reason is that we set signal handlers too (maybe the one you intend to use is something we're not using -- I'm not very familiar with this part of our code) and that we stuff with memory protection too / I didn't think you could do that on a `&[u8]` 🤔.

I'm not sure if you're familiar with this code: https://github.com/wasmerio/wasmer/blob/master/lib/runtime-core/src/sys/unix/memory.rs ; I wasn't familiar with it until today.

If there is a quick to implement solution that is minimally invasive*, I think that's the path we want to take so that we're not blocking your use case.  In the longer term, we'll want to make a more robust API for this.

*: we want to minimize API breakage in general, so we don't want to add anything that's clearly a temporary hack with no other uses.

----

That's an interesting point about Windows.  I should get a Windows development environment set up so I can be more aware of these issues.

**Comment by syrusakbary** [comment]
In the new API for Wasmer 1.0, you can customize the way Memory works via [`Tunables`](https://github.com/wasmerio/wasmer/blob/master/examples/tunables_limit_memory.rs) and a custom memory implementation (as long as it satisfies the `Memory` trait).

Closing the issue
