### ISSUE TITLE
load/save LLVM IR when using the LLVM backend

### ISSUE THREAD

**Issue by jianguda** [wasmerio/wasmer#871]
### Motivation

We are doing some exploration work of optimization/randomization for WebAssembly, based on LLVM, and these work would be seen as dynamic enhancements of WebAssembly. If wasmer supports load/save LLVM IR, then lots of experiments from many teams could launch directly on wasmer. This feature could bridge different areas and create win-win.

### Proposed solution

As we already have implementations of code generator, namely [lib/runtime-core/src/codegen.rs](https://github.com/wasmerio/wasmer/blob/master/lib/runtime-core/src/codegen.rs) and [lib/llvm-backend/src/code.rs](https://github.com/wasmerio/wasmer/blob/master/lib/llvm-backend/src/code.rs), then we need implementing persistence utility functions to load/save corresponding structures, in the format of LLVM IR.

### Alternatives

None.

### Additional context

None.

**Comment by syrusakbary** [comment]
Hi @jianguda,

Thanks for opening the issue! Right now we support dumping the LLVM IR (save) into a file for debugging proposes with the `--backend-llvm-object-file` when running with the Wasmer binary.

https://github.com/wasmerio/wasmer/blob/master/src/bin/wasmer.rs#L111-L113

However we have less context on what you mean with `loading` LLVM IR, and we would love to learn more.
If you could give examples on how you would like to use it with Wasmer (what kind of APIs would be needed), and what are the use cases that require loading LLVM IR that would be great.

Thanks!

**Comment by nlewycky** [comment]
We're supposed to have some LLVM backend debug flags, but they were broken. The fix is pending in PR #872.

We have three save mechanisms in the llvm-backend, `--llvm-pre-opt-ir=<filename>`, `--llvm-post-opt-ir=<filename>` and `--llvm-object-file=<filename>` which emit textual LLVM IR before and after optimization and the final generated object file as a valid `.o` you could send to a linker. Note: wasmer caches its output, so if you run twice we will skip the llvm-backend and these flags won't do anything. Make sure to pass `--disable-cache` if you're experimenting with changes to the llvm code emission.

What do you expect out of loading? The generated LLVM IR is tied to the context, and I plan to make it even more so (for example, hard-coding the pointer to the allocated Context object as a Constant) in the future. Basically, it would have to load back in to the same unix process that saved it. Would it be enough to give you a hook to run your own transformation over the LLVM IR?

Ideally, I'd rather you took the llvm-post-opt-ir and fed it into souper to find missed optimizations and implement those in LLVM then rebuild wasmer. Would that work for you?

**Comment by jianguda** [comment]
> Ideally, I'd rather you took the llvm-post-opt-ir and fed it into souper to find missed optimizations and implement those in LLVM then rebuild wasmer. Would that work for you?

It sounds more reasonable. Thanks!
