### ISSUE TITLE
Passing structs between instance and host?

### ISSUE THREAD

**Issue by caelunshun** [wasmerio/wasmer#958]
As I've begun prototyping the plugin API for [Feather](https://github.com/feather-rs/feather), I've noticed that there doesn't seem to be support for passing structs to WASM modules. I haven't found any documentation on the WASI spec or the `wasmer` docs regarding this, so I'm assuming there's no support for it yet.

I believe it should be possible to heap-allocate structs and pass them as pointers, but this is somewhat wasteful. While I can do this for now, performance is critical for my use case, so are there any plans to pass structs over the stack in the future?

**Comment by MarkMcCaskey** [comment]
Hey!  Glad to hear you're prototyping it!  Feel free to ping me if you need any help at all or just want to talk about it!

Hmm, so it depends on the direction.

For the Guest -> Host, it's perfectly valid right now to pass a pointer to Wasm stack memory and that shouldn't have much overhead.

For Host -> Guest, it is true that you'd have to write to some place in Wasm memory and pass it along.

It's probably possible to use trampolines to do this today, but that may not be the optimization you were hoping for.  I did some investigation and on Rust 1.39.0 compiling to `wasm32-unknown-unknown` in release mode:

```Rust
#[repr(C)]
pub struct MyStruct(usize, usize, usize);

#[no_mangle]
fn my_func(a: MyStruct) -> usize {
    a.0 + a.1 + a.2
}
```

Compiles to

```wasm
  (type (;5;) (func (param i32) (result i32)))
  (func $my_func (type 5) (param i32) (result i32)
    local.get 0
    i32.load offset=4
    local.get 0
    i32.load
    i32.add
    local.get 0
    i32.load offset=8
    i32.add)
```

This kind of optimization is definitely something that applies to Wasm generally and not WASI.

Without multiple return values, it looks like Rust will generate the code to pass results back via pointer, too:

```Rust
pub struct MyStruct(usize, usize, usize);

#[no_mangle]
fn my_func(a: MyStruct) -> u128 {
    (a.0 + a.1 + a.2) as u128
}
```

compiles to

```wasm
  (type (;4;) (func (param i32 i32)))
  (func $my_func (type 4) (param i32 i32)
    local.get 0
    i64.const 0
    i64.store offset=8
    local.get 0
    local.get 1
    i32.load offset=4
    local.get 1
    i32.load
    i32.add
    local.get 1
    i32.load offset=8
    i32.add
    i64.extend_i32_u
    i64.store)
```

It'd also be possible to destructure and restructure structs with proc macros today.  That could potentially be faster, but I'd have no idea until we benchmarked it.

I think the biggest win for Host -> Guest will be to have multiple return values.  That way a large amount of data can be passed back directly.  As I mentioned above, Rust will generate this code for you on the Wasm side, but you can also write it yourself if you want full control over it.  Unfortunately, this transformation is something that the host wouldn't be able to know about.  But it is possible to pass your arguments back via guest-allocated and passed pointer.  That's a common pattern in the WASI syscalls and can avoid having to allocate things on the heap.

So on the guest side you could do something like:

```Rust
let mut out = MyStruct::default();
host_call(&mut out);
```

----

to answer your original question: I think multiple return values and possibly future optimization work after interface types become stable may make this happen.

**Comment by caelunshun** [comment]
Thanks! So as I hear it, passing structs from stack memory on the guest to the host should work fine, while passing from host to guest currently requires passing a pointer. This will do fine for now for our purposes, although it would be nice to avoid the heap allocation in the future.

I can't figure out how to allocate a struct in the WASM module's memory, though—I see `MemoryView` provides functions to access individual bytes, but no functions to allocate a block of memory (like `malloc()`). Is this supposed to be implemented by the user, or is there something I'm missing?

**Comment by MarkMcCaskey** [comment]
In this case, I think it's still "in memory", the Wasm stack is more limited probably isn't what you'd want to use here.  The reason I think that is because it's passing a pointer and pointers in Wasm are relative to memories, not the stack (which is its own thing that is not in memory).

> Can this be relied on, or is it an implementation detail which could change?

I assume it will change when multiple return values stabilizes, so it's best to be explicit if avoiding breakage is something you want!

Yeah, so memory allocation is ABI specific.  Pure WASI doesn't provide memory allocation calls of any kind.  You can extend WASI and add your own (Rust compiles its own in to the wasm, so you can just like allocate a `Vec<u8>`, get a pointer and `mem::forget` it for a hacky and minimal malloc / free set up).  Emscripten, for example, does have malloc and free as part of it, but I don't think that's a good fit for your use case as I understand it.

WASI vs plain Wasm is something to decide on though.  Most of what WASI offers is a file system abstraction and a capability system, if you don't need those then you may be better off with plain wasm32-unknown-unknown + your custom imports/exports.  A nice benefit of WASI though is that things like printing to stdout "just work" and with Wasmer, you can control where stdout goes.

If your scripts will operate kind of like programs running in sandbox, then WASI is a good choice (though it technically doesn't support being used as a library yet so we'll need some hacks to make it work), otherwise if you just need pure computation wasm32-unknown-unknown is a blank slate.
