### ISSUE TITLE
How does metering work across various backends?

### ISSUE THREAD

**Issue by AdamSLevy** [wasmerio/wasmer#982]
### Summary
I am looking into how metering works across the various backends so that I can make some decisions about whether it will meet the needs of my application.

At a high level, I understand that metering generally involves summing up the "cost" of each opcode within each sequence of code, where a sequence is defined as a sequence of opcodes up to a branching opcode. At the beginning of each sequence at runtime, a running limit can be checked against the subsequent cost of the sequence, and if it will not be exceeded, the limit can be deduced and the sequence may proceed.

I am relatively new to rust, so I'm learning as I go here, but I tracked down the middleware metering code defined here: 

https://github.com/wasmerio/wasmer/blob/41c1e071c801e57269ea62fb5290fb316fd8f2a6/lib/middleware-common/src/metering.rs#L40-L110

 While I'm struggling a bit with the syntax, I generally get that this is matching opcodes that are streaming in on an EventSink. I can see that we are matching against branching opcodes, but I see no summing of costs of other opcodes. Is this deliberately omitted or am I looking in the wrong place? Is that implemented by the selected backend instead?

Is there a way to establish an opcode cost table so that specific opcodes have higher or lower cost? 

When a host function is called, how can it subtract its own cost from the running limit? 

How inefficient is it to be instantiating new instances with metering enabled with a reset limit each time, like in the case of a blockchain setting up a fresh execution environment for a smart contract call?

I much appreciate any input and would be happy to contribute back what I learn in the form of some additional documentation.

**Comment by bjfish** [comment]
> Is this deliberately omitted or am I looking in the wrong place? Is that implemented by the selected backend instead?

The `self.current_block += 1; ` is incremented for every wasm opcode.

> Is there a way to establish an opcode cost table so that specific opcodes have higher or lower cost?

This is possible but it is not currently implemented.  We found using a single cost to be common in other metering implementations.

> When a host function is called, how can it subtract its own cost from the running limit?

See the test examples on how metering can be used: https://github.com/wasmerio/wasmer/blob/f68ad7f655c3d219c9631a347b8379a69c33f939/lib/middleware-common-tests/src/lib.rs#L1.

> How inefficient is it to be instantiating new instances with metering enabled with a reset limit each time, like in the case of a blockchain setting up a fresh execution environment for a smart contract call?

Instances can be re-used by resetting metering back to zero with the API shown in the test cases above.  However, creating new instances should not be too high overhead as well.

One common way of doing metering in web assembly is to modify web assembly binaries to inject metering costs within an existing wasm opcodes and add host functions to track costs and trap early if necessary.  This would also be possible with wasmer since it uses normal web assembly operations.

The Wasmer metering middleware functionality implements this same functionality but metering machine code inlined into the functions machine code. This results in a large reduction in the performance overhead of metering by removing the need for host calls.

The [feature matrix](https://github.com/wasmerio/wasmer/blob/master/docs/feature_matrix.md) shows which backends currently implement metering.

**Comment by AdamSLevy** [comment]
Of course now that it is pointed out to me, the line `self.current_block += 1;` seems exceedingly obvious. 

Thank you very much for your reply. It was very helpful.

**Comment by jcaesar** [comment]
Might be a bit late for an answer, but..

> However, creating new instances should not be too high overhead as well.

Just to add some numbers to this: If I do it in a single thread, I can create about 1 instance per us. Parallel/Concurrent creation only gives me 1 every 2 us.
